#1. QUERY DE LOGIN: Pública para verificar credenciales
query GetUsuarioByCorreo($correo: String!) @auth(level: PUBLIC) {
  usuarios(where: { correo: { eq: $correo } }) {
    usuarioId  
    nombreCompleto
    correo
    passwordHash
    rol {
      nombre
    }
  }
}

# 2. BUSCAR ESTUDIANTE POR MATRÍCULA
query BuscarEstudiantePorMatricula($matricula: String!) @auth(level: USER) {
  estudiantes(where: { matricula: { eq: $matricula } }) {
    matricula
    usuario {  # 👈 Entramos a la relación para sacar los datos reales
      usuarioId
      nombreCompleto
      correo
      activo
    }
  }
}

# 3. BUSCAR ESTUDIANTE POR NOMBRE
query BuscarEstudiantePorNombre($nombre: String!) @auth(level: USER) {
  estudiantes(
    where: {
      usuario: { nombreCompleto: { contains: $nombre } } # 👈 El filtro correcto se aplica en el usuario
    }
  ) {
    matricula
    usuario {
      nombreCompleto
      correo
    }
  }
}

# 4. LISTAR TODOS LOS ESTUDIANTES
query ListarEstudiantes @auth(level: USER) {
  estudiantes {
    matricula
    usuario {
      nombreCompleto
      correo
      activo
    }
  }
}