extend type Asistencia {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "Asistencia", purpose: IMPLICIT_KEY_FIELD)
  """
  ✨ Implicit foreign key field based on `Asistencia`.`estudiante`. It must match the value of `Estudiante`.`id`. See `@ref` for how to customize it.
  """
  estudianteId: UUID! @fdc_generated(from: "Asistencia.estudiante", purpose: IMPLICIT_REF_FIELD)
  """
  ✨ Implicit foreign key field based on `Asistencia`.`instructor`. It must match the value of `Instructor`.`id`. See `@ref` for how to customize it.
  """
  instructorId: UUID! @fdc_generated(from: "Asistencia.instructor", purpose: IMPLICIT_REF_FIELD)
}
extend type Curso {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "Curso", purpose: IMPLICIT_KEY_FIELD)
}
extend type Estudiante {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "Estudiante", purpose: IMPLICIT_KEY_FIELD)
}
extend type Horario {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "Horario", purpose: IMPLICIT_KEY_FIELD)
  """
  ✨ Implicit foreign key field based on `Horario`.`curso`. It must match the value of `Curso`.`id`. See `@ref` for how to customize it.
  """
  cursoId: UUID! @fdc_generated(from: "Horario.curso", purpose: IMPLICIT_REF_FIELD)
}
extend type Inscripcion {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "Inscripcion", purpose: IMPLICIT_KEY_FIELD)
  """
  ✨ Implicit foreign key field based on `Inscripcion`.`estudiante`. It must match the value of `Estudiante`.`id`. See `@ref` for how to customize it.
  """
  estudianteId: UUID! @fdc_generated(from: "Inscripcion.estudiante", purpose: IMPLICIT_REF_FIELD)
  """
  ✨ Implicit foreign key field based on `Inscripcion`.`horario`. It must match the value of `Horario`.`id`. See `@ref` for how to customize it.
  """
  horarioId: UUID! @fdc_generated(from: "Inscripcion.horario", purpose: IMPLICIT_REF_FIELD)
}
extend type Instructor {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "Instructor", purpose: IMPLICIT_KEY_FIELD)
}
extend type ReporteEstadistica {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "ReporteEstadistica", purpose: IMPLICIT_KEY_FIELD)
  """
  ✨ Implicit foreign key field based on `ReporteEstadistica`.`curso`. It must match the value of `Curso`.`id`. See `@ref` for how to customize it.
  """
  cursoId: UUID! @fdc_generated(from: "ReporteEstadistica.curso", purpose: IMPLICIT_REF_FIELD)
}
