"""
✨ `Asistencia_KeyOutput` returns the primary key fields of table type `Asistencia`.

It has the same format as `Asistencia_Key`, but is only used as mutation return value.
"""
scalar Asistencia_KeyOutput
"""
✨ `Curso_KeyOutput` returns the primary key fields of table type `Curso`.

It has the same format as `Curso_Key`, but is only used as mutation return value.
"""
scalar Curso_KeyOutput
"""
✨ `Estudiante_KeyOutput` returns the primary key fields of table type `Estudiante`.

It has the same format as `Estudiante_Key`, but is only used as mutation return value.
"""
scalar Estudiante_KeyOutput
"""
✨ `Horario_KeyOutput` returns the primary key fields of table type `Horario`.

It has the same format as `Horario_Key`, but is only used as mutation return value.
"""
scalar Horario_KeyOutput
"""
✨ `Inscripcion_KeyOutput` returns the primary key fields of table type `Inscripcion`.

It has the same format as `Inscripcion_Key`, but is only used as mutation return value.
"""
scalar Inscripcion_KeyOutput
"""
✨ `Instructor_KeyOutput` returns the primary key fields of table type `Instructor`.

It has the same format as `Instructor_Key`, but is only used as mutation return value.
"""
scalar Instructor_KeyOutput
"""
✨ `ReporteEstadistica_KeyOutput` returns the primary key fields of table type `ReporteEstadistica`.

It has the same format as `ReporteEstadistica_Key`, but is only used as mutation return value.
"""
scalar ReporteEstadistica_KeyOutput
"""
✨ Generated data input type for table 'Asistencia'. It includes all necessary fields for creating or upserting rows into table.
"""
input Asistencia_Data {
  """
  ✨ Generated from Field `Asistencia`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `Asistencia`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Asistencia`.`estudianteId` of type `UUID!`
  """
  estudianteId: UUID
  """
  ✨ `_expr` server value variant of `estudianteId` (✨ Generated from Field `Asistencia`.`estudianteId` of type `UUID!`)
  """
  estudianteId_expr: UUID_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Asistencia`.`instructorId` of type `UUID!`
  """
  instructorId: UUID
  """
  ✨ `_expr` server value variant of `instructorId` (✨ Generated from Field `Asistencia`.`instructorId` of type `UUID!`)
  """
  instructorId_expr: UUID_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Asistencia`.`estudiante` of type `Estudiante!`
  """
  estudiante: Estudiante_Key @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Asistencia`.`instructor` of type `Instructor!`
  """
  instructor: Instructor_Key @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Asistencia`.`asistenciaId` of type `Int!`
  """
  asistenciaId: Int
  """
  ✨ `_expr` server value variant of `asistenciaId` (✨ Generated from Field `Asistencia`.`asistenciaId` of type `Int!`)
  """
  asistenciaId_expr: Int_Expr @fdc_forbiddenInVariables
  """
  ✨ `_update` server value variant of `asistenciaId` (✨ Generated from Field `Asistencia`.`asistenciaId` of type `Int!`)
  """
  asistenciaId_update: [Int_Update!] @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Asistencia`.`estadoAsistencia` of type `String!`
  """
  estadoAsistencia: String
  """
  ✨ `_expr` server value variant of `estadoAsistencia` (✨ Generated from Field `Asistencia`.`estadoAsistencia` of type `String!`)
  """
  estadoAsistencia_expr: String_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Asistencia`.`fecha` of type `Date!`
  """
  fecha: Date
  """
  ✨ `_date` server value variant of `fecha` (✨ Generated from Field `Asistencia`.`fecha` of type `Date!`)
  """
  fecha_date: Date_Relative @fdc_forbiddenInVariables
  """
  ✨ `_expr` server value variant of `fecha` (✨ Generated from Field `Asistencia`.`fecha` of type `Date!`)
  """
  fecha_expr: Date_Expr @fdc_forbiddenInVariables
  """
  ✨ `_update` server value variant of `fecha` (✨ Generated from Field `Asistencia`.`fecha` of type `Date!`)
  """
  fecha_update: [Date_Update!] @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Asistencia`.`materiaId` of type `Int!`
  """
  materiaId: Int
  """
  ✨ `_expr` server value variant of `materiaId` (✨ Generated from Field `Asistencia`.`materiaId` of type `Int!`)
  """
  materiaId_expr: Int_Expr @fdc_forbiddenInVariables
  """
  ✨ `_update` server value variant of `materiaId` (✨ Generated from Field `Asistencia`.`materiaId` of type `Int!`)
  """
  materiaId_update: [Int_Update!] @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Asistencia`.`observaciones` of type `String`
  """
  observaciones: String
  """
  ✨ `_expr` server value variant of `observaciones` (✨ Generated from Field `Asistencia`.`observaciones` of type `String`)
  """
  observaciones_expr: String_Expr @fdc_forbiddenInVariables
}
"""
✨ Generated filter input type for table 'Asistencia'. This input allows filtering objects using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input Asistencia_Filter {
  """
  Apply multiple filter conditions using `AND` logic.
  """
  _and: [Asistencia_Filter!]
  """
  Negate the result of the provided filter condition.
  """
  _not: Asistencia_Filter
  """
  Apply multiple filter conditions using `OR` logic.
  """
  _or: [Asistencia_Filter!]
  """
  ✨ Generated from Field `Asistencia`.`id` of type `UUID!`
  """
  id: UUID_Filter
  """
  ✨ Generated from Field `Asistencia`.`estudianteId` of type `UUID!`
  """
  estudianteId: UUID_Filter
  """
  ✨ Generated from Field `Asistencia`.`instructorId` of type `UUID!`
  """
  instructorId: UUID_Filter
  """
  ✨ Generated from Field `Asistencia`.`estudiante` of type `Estudiante!`
  """
  estudiante: Estudiante_Filter
  """
  ✨ Generated from Field `Asistencia`.`instructor` of type `Instructor!`
  """
  instructor: Instructor_Filter
  """
  ✨ Generated from Field `Asistencia`.`asistenciaId` of type `Int!`
  """
  asistenciaId: Int_Filter
  """
  ✨ Generated from Field `Asistencia`.`estadoAsistencia` of type `String!`
  """
  estadoAsistencia: String_Filter
  """
  ✨ Generated from Field `Asistencia`.`fecha` of type `Date!`
  """
  fecha: Date_Filter
  """
  ✨ Generated from Field `Asistencia`.`materiaId` of type `Int!`
  """
  materiaId: Int_Filter
  """
  ✨ Generated from Field `Asistencia`.`observaciones` of type `String`
  """
  observaciones: String_Filter
}
"""
✨ Generated first-row input type for table 'Asistencia'. This input selects the first row matching the filter criteria, ordered according to the specified conditions.
"""
input Asistencia_FirstRow {
  """
  Order the result by the specified fields.
  """
  orderBy: [Asistencia_Order!]
  """
  Filters rows based on the specified conditions.
  """
  where: Asistencia_Filter
}
"""
✨ Generated having input type for table 'Asistencia'. This input allows you to filter groups during aggregate queries using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input Asistencia_Having {
  """
  Apply multiple Having conditions using `AND` logic.
  """
  _and: [Asistencia_Having!]
  """
  Whether to apply DISTINCT to the aggregate function.
  """
  _distinct: Boolean
  """
  Negate the result of the provided Having condition.
  """
  _not: Asistencia_Having
  """
  Apply multiple Having conditions using `OR` logic.
  """
  _or: [Asistencia_Having!]
  """
  ✨ Generated from Field `Asistencia`.`_count` of type `Int!`
  """
  _count: Int_Filter
  """
  ✨ Generated from Field `Asistencia`.`asistenciaId_count` of type `Int!`
  """
  asistenciaId_count: Int_Filter
  """
  ✨ Generated from Field `Asistencia`.`estadoAsistencia_count` of type `Int!`
  """
  estadoAsistencia_count: Int_Filter
  """
  ✨ Generated from Field `Asistencia`.`estudianteId_count` of type `Int!`
  """
  estudianteId_count: Int_Filter
  """
  ✨ Generated from Field `Asistencia`.`fecha_count` of type `Int!`
  """
  fecha_count: Int_Filter
  """
  ✨ Generated from Field `Asistencia`.`id_count` of type `Int!`
  """
  id_count: Int_Filter
  """
  ✨ Generated from Field `Asistencia`.`instructorId_count` of type `Int!`
  """
  instructorId_count: Int_Filter
  """
  ✨ Generated from Field `Asistencia`.`materiaId_count` of type `Int!`
  """
  materiaId_count: Int_Filter
  """
  ✨ Generated from Field `Asistencia`.`observaciones_count` of type `Int!`
  """
  observaciones_count: Int_Filter
  """
  ✨ Generated from Field `Asistencia`.`asistenciaId_sum` of type `Int`
  """
  asistenciaId_sum: Int_Filter
  """
  ✨ Generated from Field `Asistencia`.`materiaId_sum` of type `Int`
  """
  materiaId_sum: Int_Filter
  """
  ✨ Generated from Field `Asistencia`.`asistenciaId_avg` of type `Float`
  """
  asistenciaId_avg: Float_Filter
  """
  ✨ Generated from Field `Asistencia`.`materiaId_avg` of type `Float`
  """
  materiaId_avg: Float_Filter
  """
  ✨ Generated from Field `Asistencia`.`asistenciaId_min` of type `Int`
  """
  asistenciaId_min: Int_Filter
  """
  ✨ Generated from Field `Asistencia`.`fecha_min` of type `Date`
  """
  fecha_min: Date_Filter
  """
  ✨ Generated from Field `Asistencia`.`materiaId_min` of type `Int`
  """
  materiaId_min: Int_Filter
  """
  ✨ Generated from Field `Asistencia`.`asistenciaId_max` of type `Int`
  """
  asistenciaId_max: Int_Filter
  """
  ✨ Generated from Field `Asistencia`.`fecha_max` of type `Date`
  """
  fecha_max: Date_Filter
  """
  ✨ Generated from Field `Asistencia`.`materiaId_max` of type `Int`
  """
  materiaId_max: Int_Filter
}
"""
✨ Generated key input type for table 'Asistencia'. It represents the primary key fields used to uniquely identify a row in the table.
"""
input Asistencia_Key {
  """
  ✨ Generated from Field `Asistencia`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `Asistencia`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr @fdc_forbiddenInVariables
}
"""
✨ Generated list filter input type for table 'Asistencia'. This input applies filtering logic based on the count or existence of related objects that matches certain criteria.
"""
input Asistencia_ListFilter {
  """
  The desired number of objects that match the condition (defaults to at least one).
  """
  count: Int_Filter = {gt:0}
  """
  Condition of the related objects to filter for.
  """
  exist: Asistencia_Filter
}
"""
✨ Generated order input type for table 'Asistencia'. This input defines the sorting order of rows in query results based on one or more fields.
"""
input Asistencia_Order {
  """
  ✨ Generated from Field `Asistencia`.`id` of type `UUID!`
  """
  id: OrderDirection
  """
  ✨ Generated from Field `Asistencia`.`estudianteId` of type `UUID!`
  """
  estudianteId: OrderDirection
  """
  ✨ Generated from Field `Asistencia`.`instructorId` of type `UUID!`
  """
  instructorId: OrderDirection
  """
  ✨ Generated from Field `Asistencia`.`estudiante` of type `Estudiante!`
  """
  estudiante: Estudiante_Order
  """
  ✨ Generated from Field `Asistencia`.`instructor` of type `Instructor!`
  """
  instructor: Instructor_Order
  """
  ✨ Generated from Field `Asistencia`.`asistenciaId` of type `Int!`
  """
  asistenciaId: OrderDirection
  """
  ✨ Generated from Field `Asistencia`.`estadoAsistencia` of type `String!`
  """
  estadoAsistencia: OrderDirection
  """
  ✨ Generated from Field `Asistencia`.`fecha` of type `Date!`
  """
  fecha: OrderDirection
  """
  ✨ Generated from Field `Asistencia`.`materiaId` of type `Int!`
  """
  materiaId: OrderDirection
  """
  ✨ Generated from Field `Asistencia`.`observaciones` of type `String`
  """
  observaciones: OrderDirection
  """
  ✨ Generated from Field `Asistencia`.`_count` of type `Int!`
  """
  _count: OrderDirection
  """
  ✨ Generated from Field `Asistencia`.`asistenciaId_count` of type `Int!`
  """
  asistenciaId_count: OrderDirection
  """
  ✨ Generated from Field `Asistencia`.`estadoAsistencia_count` of type `Int!`
  """
  estadoAsistencia_count: OrderDirection
  """
  ✨ Generated from Field `Asistencia`.`estudianteId_count` of type `Int!`
  """
  estudianteId_count: OrderDirection
  """
  ✨ Generated from Field `Asistencia`.`fecha_count` of type `Int!`
  """
  fecha_count: OrderDirection
  """
  ✨ Generated from Field `Asistencia`.`id_count` of type `Int!`
  """
  id_count: OrderDirection
  """
  ✨ Generated from Field `Asistencia`.`instructorId_count` of type `Int!`
  """
  instructorId_count: OrderDirection
  """
  ✨ Generated from Field `Asistencia`.`materiaId_count` of type `Int!`
  """
  materiaId_count: OrderDirection
  """
  ✨ Generated from Field `Asistencia`.`observaciones_count` of type `Int!`
  """
  observaciones_count: OrderDirection
  """
  ✨ Generated from Field `Asistencia`.`asistenciaId_sum` of type `Int`
  """
  asistenciaId_sum: OrderDirection
  """
  ✨ Generated from Field `Asistencia`.`materiaId_sum` of type `Int`
  """
  materiaId_sum: OrderDirection
  """
  ✨ Generated from Field `Asistencia`.`asistenciaId_avg` of type `Float`
  """
  asistenciaId_avg: OrderDirection
  """
  ✨ Generated from Field `Asistencia`.`materiaId_avg` of type `Float`
  """
  materiaId_avg: OrderDirection
  """
  ✨ Generated from Field `Asistencia`.`asistenciaId_min` of type `Int`
  """
  asistenciaId_min: OrderDirection
  """
  ✨ Generated from Field `Asistencia`.`fecha_min` of type `Date`
  """
  fecha_min: OrderDirection
  """
  ✨ Generated from Field `Asistencia`.`materiaId_min` of type `Int`
  """
  materiaId_min: OrderDirection
  """
  ✨ Generated from Field `Asistencia`.`asistenciaId_max` of type `Int`
  """
  asistenciaId_max: OrderDirection
  """
  ✨ Generated from Field `Asistencia`.`fecha_max` of type `Date`
  """
  fecha_max: OrderDirection
  """
  ✨ Generated from Field `Asistencia`.`materiaId_max` of type `Int`
  """
  materiaId_max: OrderDirection
}
"""
✨ Generated data input type for table 'Curso'. It includes all necessary fields for creating or upserting rows into table.
"""
input Curso_Data {
  """
  ✨ Generated from Field `Curso`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `Curso`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Curso`.`categoria` of type `String`
  """
  categoria: String
  """
  ✨ `_expr` server value variant of `categoria` (✨ Generated from Field `Curso`.`categoria` of type `String`)
  """
  categoria_expr: String_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Curso`.`cursoId` of type `Int!`
  """
  cursoId: Int
  """
  ✨ `_expr` server value variant of `cursoId` (✨ Generated from Field `Curso`.`cursoId` of type `Int!`)
  """
  cursoId_expr: Int_Expr @fdc_forbiddenInVariables
  """
  ✨ `_update` server value variant of `cursoId` (✨ Generated from Field `Curso`.`cursoId` of type `Int!`)
  """
  cursoId_update: [Int_Update!] @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Curso`.`descripcion` of type `String`
  """
  descripcion: String
  """
  ✨ `_expr` server value variant of `descripcion` (✨ Generated from Field `Curso`.`descripcion` of type `String`)
  """
  descripcion_expr: String_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Curso`.`estado` of type `String`
  """
  estado: String
  """
  ✨ `_expr` server value variant of `estado` (✨ Generated from Field `Curso`.`estado` of type `String`)
  """
  estado_expr: String_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Curso`.`instructor` of type `String`
  """
  instructor: String
  """
  ✨ `_expr` server value variant of `instructor` (✨ Generated from Field `Curso`.`instructor` of type `String`)
  """
  instructor_expr: String_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Curso`.`nombre` of type `String!`
  """
  nombre: String
  """
  ✨ `_expr` server value variant of `nombre` (✨ Generated from Field `Curso`.`nombre` of type `String!`)
  """
  nombre_expr: String_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Curso`.`urlImagen` of type `String`
  """
  urlImagen: String
  """
  ✨ `_expr` server value variant of `urlImagen` (✨ Generated from Field `Curso`.`urlImagen` of type `String`)
  """
  urlImagen_expr: String_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Curso`.`horarios_on_curso` of type `[Horario!]!`
  """
  horarios_on_curso: [Horario_Data!]
  """
  ✨ Generated from Field `Curso`.`reporteEstadisticas_on_curso` of type `[ReporteEstadistica!]!`
  """
  reporteEstadisticas_on_curso: [ReporteEstadistica_Data!]
}
"""
✨ Generated filter input type for table 'Curso'. This input allows filtering objects using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input Curso_Filter {
  """
  Apply multiple filter conditions using `AND` logic.
  """
  _and: [Curso_Filter!]
  """
  Negate the result of the provided filter condition.
  """
  _not: Curso_Filter
  """
  Apply multiple filter conditions using `OR` logic.
  """
  _or: [Curso_Filter!]
  """
  ✨ Generated from Field `Curso`.`id` of type `UUID!`
  """
  id: UUID_Filter
  """
  ✨ Generated from Field `Curso`.`categoria` of type `String`
  """
  categoria: String_Filter
  """
  ✨ Generated from Field `Curso`.`cursoId` of type `Int!`
  """
  cursoId: Int_Filter
  """
  ✨ Generated from Field `Curso`.`descripcion` of type `String`
  """
  descripcion: String_Filter
  """
  ✨ Generated from Field `Curso`.`estado` of type `String`
  """
  estado: String_Filter
  """
  ✨ Generated from Field `Curso`.`instructor` of type `String`
  """
  instructor: String_Filter
  """
  ✨ Generated from Field `Curso`.`nombre` of type `String!`
  """
  nombre: String_Filter
  """
  ✨ Generated from Field `Curso`.`urlImagen` of type `String`
  """
  urlImagen: String_Filter
  """
  ✨ Generated from Field `Curso`.`horarios_on_curso` of type `[Horario!]!`
  """
  horarios_on_curso: Horario_ListFilter
  """
  ✨ Generated from Field `Curso`.`reporteEstadisticas_on_curso` of type `[ReporteEstadistica!]!`
  """
  reporteEstadisticas_on_curso: ReporteEstadistica_ListFilter
}
"""
✨ Generated first-row input type for table 'Curso'. This input selects the first row matching the filter criteria, ordered according to the specified conditions.
"""
input Curso_FirstRow {
  """
  Order the result by the specified fields.
  """
  orderBy: [Curso_Order!]
  """
  Filters rows based on the specified conditions.
  """
  where: Curso_Filter
}
"""
✨ Generated having input type for table 'Curso'. This input allows you to filter groups during aggregate queries using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input Curso_Having {
  """
  Apply multiple Having conditions using `AND` logic.
  """
  _and: [Curso_Having!]
  """
  Whether to apply DISTINCT to the aggregate function.
  """
  _distinct: Boolean
  """
  Negate the result of the provided Having condition.
  """
  _not: Curso_Having
  """
  Apply multiple Having conditions using `OR` logic.
  """
  _or: [Curso_Having!]
  """
  ✨ Generated from Field `Curso`.`_count` of type `Int!`
  """
  _count: Int_Filter
  """
  ✨ Generated from Field `Curso`.`categoria_count` of type `Int!`
  """
  categoria_count: Int_Filter
  """
  ✨ Generated from Field `Curso`.`cursoId_count` of type `Int!`
  """
  cursoId_count: Int_Filter
  """
  ✨ Generated from Field `Curso`.`descripcion_count` of type `Int!`
  """
  descripcion_count: Int_Filter
  """
  ✨ Generated from Field `Curso`.`estado_count` of type `Int!`
  """
  estado_count: Int_Filter
  """
  ✨ Generated from Field `Curso`.`id_count` of type `Int!`
  """
  id_count: Int_Filter
  """
  ✨ Generated from Field `Curso`.`instructor_count` of type `Int!`
  """
  instructor_count: Int_Filter
  """
  ✨ Generated from Field `Curso`.`nombre_count` of type `Int!`
  """
  nombre_count: Int_Filter
  """
  ✨ Generated from Field `Curso`.`urlImagen_count` of type `Int!`
  """
  urlImagen_count: Int_Filter
  """
  ✨ Generated from Field `Curso`.`cursoId_sum` of type `Int`
  """
  cursoId_sum: Int_Filter
  """
  ✨ Generated from Field `Curso`.`cursoId_avg` of type `Float`
  """
  cursoId_avg: Float_Filter
  """
  ✨ Generated from Field `Curso`.`cursoId_min` of type `Int`
  """
  cursoId_min: Int_Filter
  """
  ✨ Generated from Field `Curso`.`cursoId_max` of type `Int`
  """
  cursoId_max: Int_Filter
}
"""
✨ Generated key input type for table 'Curso'. It represents the primary key fields used to uniquely identify a row in the table.
"""
input Curso_Key {
  """
  ✨ Generated from Field `Curso`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `Curso`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr @fdc_forbiddenInVariables
}
"""
✨ Generated list filter input type for table 'Curso'. This input applies filtering logic based on the count or existence of related objects that matches certain criteria.
"""
input Curso_ListFilter {
  """
  The desired number of objects that match the condition (defaults to at least one).
  """
  count: Int_Filter = {gt:0}
  """
  Condition of the related objects to filter for.
  """
  exist: Curso_Filter
}
"""
✨ Generated order input type for table 'Curso'. This input defines the sorting order of rows in query results based on one or more fields.
"""
input Curso_Order {
  """
  ✨ Generated from Field `Curso`.`id` of type `UUID!`
  """
  id: OrderDirection
  """
  ✨ Generated from Field `Curso`.`categoria` of type `String`
  """
  categoria: OrderDirection
  """
  ✨ Generated from Field `Curso`.`cursoId` of type `Int!`
  """
  cursoId: OrderDirection
  """
  ✨ Generated from Field `Curso`.`descripcion` of type `String`
  """
  descripcion: OrderDirection
  """
  ✨ Generated from Field `Curso`.`estado` of type `String`
  """
  estado: OrderDirection
  """
  ✨ Generated from Field `Curso`.`instructor` of type `String`
  """
  instructor: OrderDirection
  """
  ✨ Generated from Field `Curso`.`nombre` of type `String!`
  """
  nombre: OrderDirection
  """
  ✨ Generated from Field `Curso`.`urlImagen` of type `String`
  """
  urlImagen: OrderDirection
  """
  ✨ Generated from Field `Curso`.`_count` of type `Int!`
  """
  _count: OrderDirection
  """
  ✨ Generated from Field `Curso`.`categoria_count` of type `Int!`
  """
  categoria_count: OrderDirection
  """
  ✨ Generated from Field `Curso`.`cursoId_count` of type `Int!`
  """
  cursoId_count: OrderDirection
  """
  ✨ Generated from Field `Curso`.`descripcion_count` of type `Int!`
  """
  descripcion_count: OrderDirection
  """
  ✨ Generated from Field `Curso`.`estado_count` of type `Int!`
  """
  estado_count: OrderDirection
  """
  ✨ Generated from Field `Curso`.`id_count` of type `Int!`
  """
  id_count: OrderDirection
  """
  ✨ Generated from Field `Curso`.`instructor_count` of type `Int!`
  """
  instructor_count: OrderDirection
  """
  ✨ Generated from Field `Curso`.`nombre_count` of type `Int!`
  """
  nombre_count: OrderDirection
  """
  ✨ Generated from Field `Curso`.`urlImagen_count` of type `Int!`
  """
  urlImagen_count: OrderDirection
  """
  ✨ Generated from Field `Curso`.`cursoId_sum` of type `Int`
  """
  cursoId_sum: OrderDirection
  """
  ✨ Generated from Field `Curso`.`cursoId_avg` of type `Float`
  """
  cursoId_avg: OrderDirection
  """
  ✨ Generated from Field `Curso`.`cursoId_min` of type `Int`
  """
  cursoId_min: OrderDirection
  """
  ✨ Generated from Field `Curso`.`cursoId_max` of type `Int`
  """
  cursoId_max: OrderDirection
}
"""
✨ Generated data input type for table 'Estudiante'. It includes all necessary fields for creating or upserting rows into table.
"""
input Estudiante_Data {
  """
  ✨ Generated from Field `Estudiante`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `Estudiante`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Estudiante`.`activo` of type `Boolean!`
  """
  activo: Boolean
  """
  ✨ `_expr` server value variant of `activo` (✨ Generated from Field `Estudiante`.`activo` of type `Boolean!`)
  """
  activo_expr: Boolean_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Estudiante`.`correo` of type `String!`
  """
  correo: String
  """
  ✨ `_expr` server value variant of `correo` (✨ Generated from Field `Estudiante`.`correo` of type `String!`)
  """
  correo_expr: String_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Estudiante`.`direccion` of type `String`
  """
  direccion: String
  """
  ✨ `_expr` server value variant of `direccion` (✨ Generated from Field `Estudiante`.`direccion` of type `String`)
  """
  direccion_expr: String_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Estudiante`.`fechaNacimiento` of type `Date`
  """
  fechaNacimiento: Date
  """
  ✨ `_date` server value variant of `fechaNacimiento` (✨ Generated from Field `Estudiante`.`fechaNacimiento` of type `Date`)
  """
  fechaNacimiento_date: Date_Relative @fdc_forbiddenInVariables
  """
  ✨ `_expr` server value variant of `fechaNacimiento` (✨ Generated from Field `Estudiante`.`fechaNacimiento` of type `Date`)
  """
  fechaNacimiento_expr: Date_Expr @fdc_forbiddenInVariables
  """
  ✨ `_update` server value variant of `fechaNacimiento` (✨ Generated from Field `Estudiante`.`fechaNacimiento` of type `Date`)
  """
  fechaNacimiento_update: [Date_Update!] @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Estudiante`.`fechaRegistro` of type `Date!`
  """
  fechaRegistro: Date
  """
  ✨ `_date` server value variant of `fechaRegistro` (✨ Generated from Field `Estudiante`.`fechaRegistro` of type `Date!`)
  """
  fechaRegistro_date: Date_Relative @fdc_forbiddenInVariables
  """
  ✨ `_expr` server value variant of `fechaRegistro` (✨ Generated from Field `Estudiante`.`fechaRegistro` of type `Date!`)
  """
  fechaRegistro_expr: Date_Expr @fdc_forbiddenInVariables
  """
  ✨ `_update` server value variant of `fechaRegistro` (✨ Generated from Field `Estudiante`.`fechaRegistro` of type `Date!`)
  """
  fechaRegistro_update: [Date_Update!] @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Estudiante`.`matricula` of type `String!`
  """
  matricula: String
  """
  ✨ `_expr` server value variant of `matricula` (✨ Generated from Field `Estudiante`.`matricula` of type `String!`)
  """
  matricula_expr: String_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Estudiante`.`nombreCompleto` of type `String!`
  """
  nombreCompleto: String
  """
  ✨ `_expr` server value variant of `nombreCompleto` (✨ Generated from Field `Estudiante`.`nombreCompleto` of type `String!`)
  """
  nombreCompleto_expr: String_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Estudiante`.`telefono` of type `String`
  """
  telefono: String
  """
  ✨ `_expr` server value variant of `telefono` (✨ Generated from Field `Estudiante`.`telefono` of type `String`)
  """
  telefono_expr: String_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Estudiante`.`asistencias_on_estudiante` of type `[Asistencia!]!`
  """
  asistencias_on_estudiante: [Asistencia_Data!]
  """
  ✨ Generated from Field `Estudiante`.`inscripcions_on_estudiante` of type `[Inscripcion!]!`
  """
  inscripcions_on_estudiante: [Inscripcion_Data!]
}
"""
✨ Generated filter input type for table 'Estudiante'. This input allows filtering objects using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input Estudiante_Filter {
  """
  Apply multiple filter conditions using `AND` logic.
  """
  _and: [Estudiante_Filter!]
  """
  Negate the result of the provided filter condition.
  """
  _not: Estudiante_Filter
  """
  Apply multiple filter conditions using `OR` logic.
  """
  _or: [Estudiante_Filter!]
  """
  ✨ Generated from Field `Estudiante`.`id` of type `UUID!`
  """
  id: UUID_Filter
  """
  ✨ Generated from Field `Estudiante`.`activo` of type `Boolean!`
  """
  activo: Boolean_Filter
  """
  ✨ Generated from Field `Estudiante`.`correo` of type `String!`
  """
  correo: String_Filter
  """
  ✨ Generated from Field `Estudiante`.`direccion` of type `String`
  """
  direccion: String_Filter
  """
  ✨ Generated from Field `Estudiante`.`fechaNacimiento` of type `Date`
  """
  fechaNacimiento: Date_Filter
  """
  ✨ Generated from Field `Estudiante`.`fechaRegistro` of type `Date!`
  """
  fechaRegistro: Date_Filter
  """
  ✨ Generated from Field `Estudiante`.`matricula` of type `String!`
  """
  matricula: String_Filter
  """
  ✨ Generated from Field `Estudiante`.`nombreCompleto` of type `String!`
  """
  nombreCompleto: String_Filter
  """
  ✨ Generated from Field `Estudiante`.`telefono` of type `String`
  """
  telefono: String_Filter
  """
  ✨ Generated from Field `Estudiante`.`asistencias_on_estudiante` of type `[Asistencia!]!`
  """
  asistencias_on_estudiante: Asistencia_ListFilter
  """
  ✨ Generated from Field `Estudiante`.`inscripcions_on_estudiante` of type `[Inscripcion!]!`
  """
  inscripcions_on_estudiante: Inscripcion_ListFilter
}
"""
✨ Generated first-row input type for table 'Estudiante'. This input selects the first row matching the filter criteria, ordered according to the specified conditions.
"""
input Estudiante_FirstRow {
  """
  Order the result by the specified fields.
  """
  orderBy: [Estudiante_Order!]
  """
  Filters rows based on the specified conditions.
  """
  where: Estudiante_Filter
}
"""
✨ Generated having input type for table 'Estudiante'. This input allows you to filter groups during aggregate queries using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input Estudiante_Having {
  """
  Apply multiple Having conditions using `AND` logic.
  """
  _and: [Estudiante_Having!]
  """
  Whether to apply DISTINCT to the aggregate function.
  """
  _distinct: Boolean
  """
  Negate the result of the provided Having condition.
  """
  _not: Estudiante_Having
  """
  Apply multiple Having conditions using `OR` logic.
  """
  _or: [Estudiante_Having!]
  """
  ✨ Generated from Field `Estudiante`.`_count` of type `Int!`
  """
  _count: Int_Filter
  """
  ✨ Generated from Field `Estudiante`.`activo_count` of type `Int!`
  """
  activo_count: Int_Filter
  """
  ✨ Generated from Field `Estudiante`.`correo_count` of type `Int!`
  """
  correo_count: Int_Filter
  """
  ✨ Generated from Field `Estudiante`.`direccion_count` of type `Int!`
  """
  direccion_count: Int_Filter
  """
  ✨ Generated from Field `Estudiante`.`fechaNacimiento_count` of type `Int!`
  """
  fechaNacimiento_count: Int_Filter
  """
  ✨ Generated from Field `Estudiante`.`fechaRegistro_count` of type `Int!`
  """
  fechaRegistro_count: Int_Filter
  """
  ✨ Generated from Field `Estudiante`.`id_count` of type `Int!`
  """
  id_count: Int_Filter
  """
  ✨ Generated from Field `Estudiante`.`matricula_count` of type `Int!`
  """
  matricula_count: Int_Filter
  """
  ✨ Generated from Field `Estudiante`.`nombreCompleto_count` of type `Int!`
  """
  nombreCompleto_count: Int_Filter
  """
  ✨ Generated from Field `Estudiante`.`telefono_count` of type `Int!`
  """
  telefono_count: Int_Filter
  """
  ✨ Generated from Field `Estudiante`.`fechaNacimiento_min` of type `Date`
  """
  fechaNacimiento_min: Date_Filter
  """
  ✨ Generated from Field `Estudiante`.`fechaRegistro_min` of type `Date`
  """
  fechaRegistro_min: Date_Filter
  """
  ✨ Generated from Field `Estudiante`.`fechaNacimiento_max` of type `Date`
  """
  fechaNacimiento_max: Date_Filter
  """
  ✨ Generated from Field `Estudiante`.`fechaRegistro_max` of type `Date`
  """
  fechaRegistro_max: Date_Filter
}
"""
✨ Generated key input type for table 'Estudiante'. It represents the primary key fields used to uniquely identify a row in the table.
"""
input Estudiante_Key {
  """
  ✨ Generated from Field `Estudiante`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `Estudiante`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr @fdc_forbiddenInVariables
}
"""
✨ Generated list filter input type for table 'Estudiante'. This input applies filtering logic based on the count or existence of related objects that matches certain criteria.
"""
input Estudiante_ListFilter {
  """
  The desired number of objects that match the condition (defaults to at least one).
  """
  count: Int_Filter = {gt:0}
  """
  Condition of the related objects to filter for.
  """
  exist: Estudiante_Filter
}
"""
✨ Generated order input type for table 'Estudiante'. This input defines the sorting order of rows in query results based on one or more fields.
"""
input Estudiante_Order {
  """
  ✨ Generated from Field `Estudiante`.`id` of type `UUID!`
  """
  id: OrderDirection
  """
  ✨ Generated from Field `Estudiante`.`activo` of type `Boolean!`
  """
  activo: OrderDirection
  """
  ✨ Generated from Field `Estudiante`.`correo` of type `String!`
  """
  correo: OrderDirection
  """
  ✨ Generated from Field `Estudiante`.`direccion` of type `String`
  """
  direccion: OrderDirection
  """
  ✨ Generated from Field `Estudiante`.`fechaNacimiento` of type `Date`
  """
  fechaNacimiento: OrderDirection
  """
  ✨ Generated from Field `Estudiante`.`fechaRegistro` of type `Date!`
  """
  fechaRegistro: OrderDirection
  """
  ✨ Generated from Field `Estudiante`.`matricula` of type `String!`
  """
  matricula: OrderDirection
  """
  ✨ Generated from Field `Estudiante`.`nombreCompleto` of type `String!`
  """
  nombreCompleto: OrderDirection
  """
  ✨ Generated from Field `Estudiante`.`telefono` of type `String`
  """
  telefono: OrderDirection
  """
  ✨ Generated from Field `Estudiante`.`_count` of type `Int!`
  """
  _count: OrderDirection
  """
  ✨ Generated from Field `Estudiante`.`activo_count` of type `Int!`
  """
  activo_count: OrderDirection
  """
  ✨ Generated from Field `Estudiante`.`correo_count` of type `Int!`
  """
  correo_count: OrderDirection
  """
  ✨ Generated from Field `Estudiante`.`direccion_count` of type `Int!`
  """
  direccion_count: OrderDirection
  """
  ✨ Generated from Field `Estudiante`.`fechaNacimiento_count` of type `Int!`
  """
  fechaNacimiento_count: OrderDirection
  """
  ✨ Generated from Field `Estudiante`.`fechaRegistro_count` of type `Int!`
  """
  fechaRegistro_count: OrderDirection
  """
  ✨ Generated from Field `Estudiante`.`id_count` of type `Int!`
  """
  id_count: OrderDirection
  """
  ✨ Generated from Field `Estudiante`.`matricula_count` of type `Int!`
  """
  matricula_count: OrderDirection
  """
  ✨ Generated from Field `Estudiante`.`nombreCompleto_count` of type `Int!`
  """
  nombreCompleto_count: OrderDirection
  """
  ✨ Generated from Field `Estudiante`.`telefono_count` of type `Int!`
  """
  telefono_count: OrderDirection
  """
  ✨ Generated from Field `Estudiante`.`fechaNacimiento_min` of type `Date`
  """
  fechaNacimiento_min: OrderDirection
  """
  ✨ Generated from Field `Estudiante`.`fechaRegistro_min` of type `Date`
  """
  fechaRegistro_min: OrderDirection
  """
  ✨ Generated from Field `Estudiante`.`fechaNacimiento_max` of type `Date`
  """
  fechaNacimiento_max: OrderDirection
  """
  ✨ Generated from Field `Estudiante`.`fechaRegistro_max` of type `Date`
  """
  fechaRegistro_max: OrderDirection
}
"""
✨ Generated data input type for table 'Horario'. It includes all necessary fields for creating or upserting rows into table.
"""
input Horario_Data {
  """
  ✨ Generated from Field `Horario`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `Horario`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Horario`.`cursoId` of type `UUID!`
  """
  cursoId: UUID
  """
  ✨ `_expr` server value variant of `cursoId` (✨ Generated from Field `Horario`.`cursoId` of type `UUID!`)
  """
  cursoId_expr: UUID_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Horario`.`curso` of type `Curso!`
  """
  curso: Curso_Key @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Horario`.`cupoActual` of type `Int!`
  """
  cupoActual: Int
  """
  ✨ `_expr` server value variant of `cupoActual` (✨ Generated from Field `Horario`.`cupoActual` of type `Int!`)
  """
  cupoActual_expr: Int_Expr @fdc_forbiddenInVariables
  """
  ✨ `_update` server value variant of `cupoActual` (✨ Generated from Field `Horario`.`cupoActual` of type `Int!`)
  """
  cupoActual_update: [Int_Update!] @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Horario`.`cupoMaximo` of type `Int!`
  """
  cupoMaximo: Int
  """
  ✨ `_expr` server value variant of `cupoMaximo` (✨ Generated from Field `Horario`.`cupoMaximo` of type `Int!`)
  """
  cupoMaximo_expr: Int_Expr @fdc_forbiddenInVariables
  """
  ✨ `_update` server value variant of `cupoMaximo` (✨ Generated from Field `Horario`.`cupoMaximo` of type `Int!`)
  """
  cupoMaximo_update: [Int_Update!] @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Horario`.`estado` of type `String`
  """
  estado: String
  """
  ✨ `_expr` server value variant of `estado` (✨ Generated from Field `Horario`.`estado` of type `String`)
  """
  estado_expr: String_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Horario`.`fechaFin` of type `Date!`
  """
  fechaFin: Date
  """
  ✨ `_date` server value variant of `fechaFin` (✨ Generated from Field `Horario`.`fechaFin` of type `Date!`)
  """
  fechaFin_date: Date_Relative @fdc_forbiddenInVariables
  """
  ✨ `_expr` server value variant of `fechaFin` (✨ Generated from Field `Horario`.`fechaFin` of type `Date!`)
  """
  fechaFin_expr: Date_Expr @fdc_forbiddenInVariables
  """
  ✨ `_update` server value variant of `fechaFin` (✨ Generated from Field `Horario`.`fechaFin` of type `Date!`)
  """
  fechaFin_update: [Date_Update!] @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Horario`.`fechaInicio` of type `Date!`
  """
  fechaInicio: Date
  """
  ✨ `_date` server value variant of `fechaInicio` (✨ Generated from Field `Horario`.`fechaInicio` of type `Date!`)
  """
  fechaInicio_date: Date_Relative @fdc_forbiddenInVariables
  """
  ✨ `_expr` server value variant of `fechaInicio` (✨ Generated from Field `Horario`.`fechaInicio` of type `Date!`)
  """
  fechaInicio_expr: Date_Expr @fdc_forbiddenInVariables
  """
  ✨ `_update` server value variant of `fechaInicio` (✨ Generated from Field `Horario`.`fechaInicio` of type `Date!`)
  """
  fechaInicio_update: [Date_Update!] @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Horario`.`horaFin` of type `String!`
  """
  horaFin: String
  """
  ✨ `_expr` server value variant of `horaFin` (✨ Generated from Field `Horario`.`horaFin` of type `String!`)
  """
  horaFin_expr: String_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Horario`.`horaInicio` of type `String!`
  """
  horaInicio: String
  """
  ✨ `_expr` server value variant of `horaInicio` (✨ Generated from Field `Horario`.`horaInicio` of type `String!`)
  """
  horaInicio_expr: String_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Horario`.`horarioId` of type `Int!`
  """
  horarioId: Int
  """
  ✨ `_expr` server value variant of `horarioId` (✨ Generated from Field `Horario`.`horarioId` of type `Int!`)
  """
  horarioId_expr: Int_Expr @fdc_forbiddenInVariables
  """
  ✨ `_update` server value variant of `horarioId` (✨ Generated from Field `Horario`.`horarioId` of type `Int!`)
  """
  horarioId_update: [Int_Update!] @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Horario`.`inscripcions_on_horario` of type `[Inscripcion!]!`
  """
  inscripcions_on_horario: [Inscripcion_Data!]
}
"""
✨ Generated filter input type for table 'Horario'. This input allows filtering objects using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input Horario_Filter {
  """
  Apply multiple filter conditions using `AND` logic.
  """
  _and: [Horario_Filter!]
  """
  Negate the result of the provided filter condition.
  """
  _not: Horario_Filter
  """
  Apply multiple filter conditions using `OR` logic.
  """
  _or: [Horario_Filter!]
  """
  ✨ Generated from Field `Horario`.`id` of type `UUID!`
  """
  id: UUID_Filter
  """
  ✨ Generated from Field `Horario`.`cursoId` of type `UUID!`
  """
  cursoId: UUID_Filter
  """
  ✨ Generated from Field `Horario`.`curso` of type `Curso!`
  """
  curso: Curso_Filter
  """
  ✨ Generated from Field `Horario`.`cupoActual` of type `Int!`
  """
  cupoActual: Int_Filter
  """
  ✨ Generated from Field `Horario`.`cupoMaximo` of type `Int!`
  """
  cupoMaximo: Int_Filter
  """
  ✨ Generated from Field `Horario`.`estado` of type `String`
  """
  estado: String_Filter
  """
  ✨ Generated from Field `Horario`.`fechaFin` of type `Date!`
  """
  fechaFin: Date_Filter
  """
  ✨ Generated from Field `Horario`.`fechaInicio` of type `Date!`
  """
  fechaInicio: Date_Filter
  """
  ✨ Generated from Field `Horario`.`horaFin` of type `String!`
  """
  horaFin: String_Filter
  """
  ✨ Generated from Field `Horario`.`horaInicio` of type `String!`
  """
  horaInicio: String_Filter
  """
  ✨ Generated from Field `Horario`.`horarioId` of type `Int!`
  """
  horarioId: Int_Filter
  """
  ✨ Generated from Field `Horario`.`inscripcions_on_horario` of type `[Inscripcion!]!`
  """
  inscripcions_on_horario: Inscripcion_ListFilter
}
"""
✨ Generated first-row input type for table 'Horario'. This input selects the first row matching the filter criteria, ordered according to the specified conditions.
"""
input Horario_FirstRow {
  """
  Order the result by the specified fields.
  """
  orderBy: [Horario_Order!]
  """
  Filters rows based on the specified conditions.
  """
  where: Horario_Filter
}
"""
✨ Generated having input type for table 'Horario'. This input allows you to filter groups during aggregate queries using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input Horario_Having {
  """
  Apply multiple Having conditions using `AND` logic.
  """
  _and: [Horario_Having!]
  """
  Whether to apply DISTINCT to the aggregate function.
  """
  _distinct: Boolean
  """
  Negate the result of the provided Having condition.
  """
  _not: Horario_Having
  """
  Apply multiple Having conditions using `OR` logic.
  """
  _or: [Horario_Having!]
  """
  ✨ Generated from Field `Horario`.`_count` of type `Int!`
  """
  _count: Int_Filter
  """
  ✨ Generated from Field `Horario`.`cupoActual_count` of type `Int!`
  """
  cupoActual_count: Int_Filter
  """
  ✨ Generated from Field `Horario`.`cupoMaximo_count` of type `Int!`
  """
  cupoMaximo_count: Int_Filter
  """
  ✨ Generated from Field `Horario`.`cursoId_count` of type `Int!`
  """
  cursoId_count: Int_Filter
  """
  ✨ Generated from Field `Horario`.`estado_count` of type `Int!`
  """
  estado_count: Int_Filter
  """
  ✨ Generated from Field `Horario`.`fechaFin_count` of type `Int!`
  """
  fechaFin_count: Int_Filter
  """
  ✨ Generated from Field `Horario`.`fechaInicio_count` of type `Int!`
  """
  fechaInicio_count: Int_Filter
  """
  ✨ Generated from Field `Horario`.`horaFin_count` of type `Int!`
  """
  horaFin_count: Int_Filter
  """
  ✨ Generated from Field `Horario`.`horaInicio_count` of type `Int!`
  """
  horaInicio_count: Int_Filter
  """
  ✨ Generated from Field `Horario`.`horarioId_count` of type `Int!`
  """
  horarioId_count: Int_Filter
  """
  ✨ Generated from Field `Horario`.`id_count` of type `Int!`
  """
  id_count: Int_Filter
  """
  ✨ Generated from Field `Horario`.`cupoActual_sum` of type `Int`
  """
  cupoActual_sum: Int_Filter
  """
  ✨ Generated from Field `Horario`.`cupoMaximo_sum` of type `Int`
  """
  cupoMaximo_sum: Int_Filter
  """
  ✨ Generated from Field `Horario`.`horarioId_sum` of type `Int`
  """
  horarioId_sum: Int_Filter
  """
  ✨ Generated from Field `Horario`.`cupoActual_avg` of type `Float`
  """
  cupoActual_avg: Float_Filter
  """
  ✨ Generated from Field `Horario`.`cupoMaximo_avg` of type `Float`
  """
  cupoMaximo_avg: Float_Filter
  """
  ✨ Generated from Field `Horario`.`horarioId_avg` of type `Float`
  """
  horarioId_avg: Float_Filter
  """
  ✨ Generated from Field `Horario`.`cupoActual_min` of type `Int`
  """
  cupoActual_min: Int_Filter
  """
  ✨ Generated from Field `Horario`.`cupoMaximo_min` of type `Int`
  """
  cupoMaximo_min: Int_Filter
  """
  ✨ Generated from Field `Horario`.`fechaFin_min` of type `Date`
  """
  fechaFin_min: Date_Filter
  """
  ✨ Generated from Field `Horario`.`fechaInicio_min` of type `Date`
  """
  fechaInicio_min: Date_Filter
  """
  ✨ Generated from Field `Horario`.`horarioId_min` of type `Int`
  """
  horarioId_min: Int_Filter
  """
  ✨ Generated from Field `Horario`.`cupoActual_max` of type `Int`
  """
  cupoActual_max: Int_Filter
  """
  ✨ Generated from Field `Horario`.`cupoMaximo_max` of type `Int`
  """
  cupoMaximo_max: Int_Filter
  """
  ✨ Generated from Field `Horario`.`fechaFin_max` of type `Date`
  """
  fechaFin_max: Date_Filter
  """
  ✨ Generated from Field `Horario`.`fechaInicio_max` of type `Date`
  """
  fechaInicio_max: Date_Filter
  """
  ✨ Generated from Field `Horario`.`horarioId_max` of type `Int`
  """
  horarioId_max: Int_Filter
}
"""
✨ Generated key input type for table 'Horario'. It represents the primary key fields used to uniquely identify a row in the table.
"""
input Horario_Key {
  """
  ✨ Generated from Field `Horario`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `Horario`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr @fdc_forbiddenInVariables
}
"""
✨ Generated list filter input type for table 'Horario'. This input applies filtering logic based on the count or existence of related objects that matches certain criteria.
"""
input Horario_ListFilter {
  """
  The desired number of objects that match the condition (defaults to at least one).
  """
  count: Int_Filter = {gt:0}
  """
  Condition of the related objects to filter for.
  """
  exist: Horario_Filter
}
"""
✨ Generated order input type for table 'Horario'. This input defines the sorting order of rows in query results based on one or more fields.
"""
input Horario_Order {
  """
  ✨ Generated from Field `Horario`.`id` of type `UUID!`
  """
  id: OrderDirection
  """
  ✨ Generated from Field `Horario`.`cursoId` of type `UUID!`
  """
  cursoId: OrderDirection
  """
  ✨ Generated from Field `Horario`.`curso` of type `Curso!`
  """
  curso: Curso_Order
  """
  ✨ Generated from Field `Horario`.`cupoActual` of type `Int!`
  """
  cupoActual: OrderDirection
  """
  ✨ Generated from Field `Horario`.`cupoMaximo` of type `Int!`
  """
  cupoMaximo: OrderDirection
  """
  ✨ Generated from Field `Horario`.`estado` of type `String`
  """
  estado: OrderDirection
  """
  ✨ Generated from Field `Horario`.`fechaFin` of type `Date!`
  """
  fechaFin: OrderDirection
  """
  ✨ Generated from Field `Horario`.`fechaInicio` of type `Date!`
  """
  fechaInicio: OrderDirection
  """
  ✨ Generated from Field `Horario`.`horaFin` of type `String!`
  """
  horaFin: OrderDirection
  """
  ✨ Generated from Field `Horario`.`horaInicio` of type `String!`
  """
  horaInicio: OrderDirection
  """
  ✨ Generated from Field `Horario`.`horarioId` of type `Int!`
  """
  horarioId: OrderDirection
  """
  ✨ Generated from Field `Horario`.`_count` of type `Int!`
  """
  _count: OrderDirection
  """
  ✨ Generated from Field `Horario`.`cupoActual_count` of type `Int!`
  """
  cupoActual_count: OrderDirection
  """
  ✨ Generated from Field `Horario`.`cupoMaximo_count` of type `Int!`
  """
  cupoMaximo_count: OrderDirection
  """
  ✨ Generated from Field `Horario`.`cursoId_count` of type `Int!`
  """
  cursoId_count: OrderDirection
  """
  ✨ Generated from Field `Horario`.`estado_count` of type `Int!`
  """
  estado_count: OrderDirection
  """
  ✨ Generated from Field `Horario`.`fechaFin_count` of type `Int!`
  """
  fechaFin_count: OrderDirection
  """
  ✨ Generated from Field `Horario`.`fechaInicio_count` of type `Int!`
  """
  fechaInicio_count: OrderDirection
  """
  ✨ Generated from Field `Horario`.`horaFin_count` of type `Int!`
  """
  horaFin_count: OrderDirection
  """
  ✨ Generated from Field `Horario`.`horaInicio_count` of type `Int!`
  """
  horaInicio_count: OrderDirection
  """
  ✨ Generated from Field `Horario`.`horarioId_count` of type `Int!`
  """
  horarioId_count: OrderDirection
  """
  ✨ Generated from Field `Horario`.`id_count` of type `Int!`
  """
  id_count: OrderDirection
  """
  ✨ Generated from Field `Horario`.`cupoActual_sum` of type `Int`
  """
  cupoActual_sum: OrderDirection
  """
  ✨ Generated from Field `Horario`.`cupoMaximo_sum` of type `Int`
  """
  cupoMaximo_sum: OrderDirection
  """
  ✨ Generated from Field `Horario`.`horarioId_sum` of type `Int`
  """
  horarioId_sum: OrderDirection
  """
  ✨ Generated from Field `Horario`.`cupoActual_avg` of type `Float`
  """
  cupoActual_avg: OrderDirection
  """
  ✨ Generated from Field `Horario`.`cupoMaximo_avg` of type `Float`
  """
  cupoMaximo_avg: OrderDirection
  """
  ✨ Generated from Field `Horario`.`horarioId_avg` of type `Float`
  """
  horarioId_avg: OrderDirection
  """
  ✨ Generated from Field `Horario`.`cupoActual_min` of type `Int`
  """
  cupoActual_min: OrderDirection
  """
  ✨ Generated from Field `Horario`.`cupoMaximo_min` of type `Int`
  """
  cupoMaximo_min: OrderDirection
  """
  ✨ Generated from Field `Horario`.`fechaFin_min` of type `Date`
  """
  fechaFin_min: OrderDirection
  """
  ✨ Generated from Field `Horario`.`fechaInicio_min` of type `Date`
  """
  fechaInicio_min: OrderDirection
  """
  ✨ Generated from Field `Horario`.`horarioId_min` of type `Int`
  """
  horarioId_min: OrderDirection
  """
  ✨ Generated from Field `Horario`.`cupoActual_max` of type `Int`
  """
  cupoActual_max: OrderDirection
  """
  ✨ Generated from Field `Horario`.`cupoMaximo_max` of type `Int`
  """
  cupoMaximo_max: OrderDirection
  """
  ✨ Generated from Field `Horario`.`fechaFin_max` of type `Date`
  """
  fechaFin_max: OrderDirection
  """
  ✨ Generated from Field `Horario`.`fechaInicio_max` of type `Date`
  """
  fechaInicio_max: OrderDirection
  """
  ✨ Generated from Field `Horario`.`horarioId_max` of type `Int`
  """
  horarioId_max: OrderDirection
}
"""
✨ Generated data input type for table 'Inscripcion'. It includes all necessary fields for creating or upserting rows into table.
"""
input Inscripcion_Data {
  """
  ✨ Generated from Field `Inscripcion`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `Inscripcion`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Inscripcion`.`estudianteId` of type `UUID!`
  """
  estudianteId: UUID
  """
  ✨ `_expr` server value variant of `estudianteId` (✨ Generated from Field `Inscripcion`.`estudianteId` of type `UUID!`)
  """
  estudianteId_expr: UUID_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Inscripcion`.`horarioId` of type `UUID!`
  """
  horarioId: UUID
  """
  ✨ `_expr` server value variant of `horarioId` (✨ Generated from Field `Inscripcion`.`horarioId` of type `UUID!`)
  """
  horarioId_expr: UUID_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Inscripcion`.`estudiante` of type `Estudiante!`
  """
  estudiante: Estudiante_Key @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Inscripcion`.`horario` of type `Horario!`
  """
  horario: Horario_Key @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Inscripcion`.`estadoInscripcion` of type `String!`
  """
  estadoInscripcion: String
  """
  ✨ `_expr` server value variant of `estadoInscripcion` (✨ Generated from Field `Inscripcion`.`estadoInscripcion` of type `String!`)
  """
  estadoInscripcion_expr: String_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Inscripcion`.`fechaInscripcion` of type `Date!`
  """
  fechaInscripcion: Date
  """
  ✨ `_date` server value variant of `fechaInscripcion` (✨ Generated from Field `Inscripcion`.`fechaInscripcion` of type `Date!`)
  """
  fechaInscripcion_date: Date_Relative @fdc_forbiddenInVariables
  """
  ✨ `_expr` server value variant of `fechaInscripcion` (✨ Generated from Field `Inscripcion`.`fechaInscripcion` of type `Date!`)
  """
  fechaInscripcion_expr: Date_Expr @fdc_forbiddenInVariables
  """
  ✨ `_update` server value variant of `fechaInscripcion` (✨ Generated from Field `Inscripcion`.`fechaInscripcion` of type `Date!`)
  """
  fechaInscripcion_update: [Date_Update!] @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Inscripcion`.`inscripcionId` of type `String!`
  """
  inscripcionId: String
  """
  ✨ `_expr` server value variant of `inscripcionId` (✨ Generated from Field `Inscripcion`.`inscripcionId` of type `String!`)
  """
  inscripcionId_expr: String_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Inscripcion`.`pagoEstado` of type `String`
  """
  pagoEstado: String
  """
  ✨ `_expr` server value variant of `pagoEstado` (✨ Generated from Field `Inscripcion`.`pagoEstado` of type `String`)
  """
  pagoEstado_expr: String_Expr @fdc_forbiddenInVariables
}
"""
✨ Generated filter input type for table 'Inscripcion'. This input allows filtering objects using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input Inscripcion_Filter {
  """
  Apply multiple filter conditions using `AND` logic.
  """
  _and: [Inscripcion_Filter!]
  """
  Negate the result of the provided filter condition.
  """
  _not: Inscripcion_Filter
  """
  Apply multiple filter conditions using `OR` logic.
  """
  _or: [Inscripcion_Filter!]
  """
  ✨ Generated from Field `Inscripcion`.`id` of type `UUID!`
  """
  id: UUID_Filter
  """
  ✨ Generated from Field `Inscripcion`.`estudianteId` of type `UUID!`
  """
  estudianteId: UUID_Filter
  """
  ✨ Generated from Field `Inscripcion`.`horarioId` of type `UUID!`
  """
  horarioId: UUID_Filter
  """
  ✨ Generated from Field `Inscripcion`.`estudiante` of type `Estudiante!`
  """
  estudiante: Estudiante_Filter
  """
  ✨ Generated from Field `Inscripcion`.`horario` of type `Horario!`
  """
  horario: Horario_Filter
  """
  ✨ Generated from Field `Inscripcion`.`estadoInscripcion` of type `String!`
  """
  estadoInscripcion: String_Filter
  """
  ✨ Generated from Field `Inscripcion`.`fechaInscripcion` of type `Date!`
  """
  fechaInscripcion: Date_Filter
  """
  ✨ Generated from Field `Inscripcion`.`inscripcionId` of type `String!`
  """
  inscripcionId: String_Filter
  """
  ✨ Generated from Field `Inscripcion`.`pagoEstado` of type `String`
  """
  pagoEstado: String_Filter
}
"""
✨ Generated first-row input type for table 'Inscripcion'. This input selects the first row matching the filter criteria, ordered according to the specified conditions.
"""
input Inscripcion_FirstRow {
  """
  Order the result by the specified fields.
  """
  orderBy: [Inscripcion_Order!]
  """
  Filters rows based on the specified conditions.
  """
  where: Inscripcion_Filter
}
"""
✨ Generated having input type for table 'Inscripcion'. This input allows you to filter groups during aggregate queries using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input Inscripcion_Having {
  """
  Apply multiple Having conditions using `AND` logic.
  """
  _and: [Inscripcion_Having!]
  """
  Whether to apply DISTINCT to the aggregate function.
  """
  _distinct: Boolean
  """
  Negate the result of the provided Having condition.
  """
  _not: Inscripcion_Having
  """
  Apply multiple Having conditions using `OR` logic.
  """
  _or: [Inscripcion_Having!]
  """
  ✨ Generated from Field `Inscripcion`.`_count` of type `Int!`
  """
  _count: Int_Filter
  """
  ✨ Generated from Field `Inscripcion`.`estadoInscripcion_count` of type `Int!`
  """
  estadoInscripcion_count: Int_Filter
  """
  ✨ Generated from Field `Inscripcion`.`estudianteId_count` of type `Int!`
  """
  estudianteId_count: Int_Filter
  """
  ✨ Generated from Field `Inscripcion`.`fechaInscripcion_count` of type `Int!`
  """
  fechaInscripcion_count: Int_Filter
  """
  ✨ Generated from Field `Inscripcion`.`horarioId_count` of type `Int!`
  """
  horarioId_count: Int_Filter
  """
  ✨ Generated from Field `Inscripcion`.`id_count` of type `Int!`
  """
  id_count: Int_Filter
  """
  ✨ Generated from Field `Inscripcion`.`inscripcionId_count` of type `Int!`
  """
  inscripcionId_count: Int_Filter
  """
  ✨ Generated from Field `Inscripcion`.`pagoEstado_count` of type `Int!`
  """
  pagoEstado_count: Int_Filter
  """
  ✨ Generated from Field `Inscripcion`.`fechaInscripcion_min` of type `Date`
  """
  fechaInscripcion_min: Date_Filter
  """
  ✨ Generated from Field `Inscripcion`.`fechaInscripcion_max` of type `Date`
  """
  fechaInscripcion_max: Date_Filter
}
"""
✨ Generated key input type for table 'Inscripcion'. It represents the primary key fields used to uniquely identify a row in the table.
"""
input Inscripcion_Key {
  """
  ✨ Generated from Field `Inscripcion`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `Inscripcion`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr @fdc_forbiddenInVariables
}
"""
✨ Generated list filter input type for table 'Inscripcion'. This input applies filtering logic based on the count or existence of related objects that matches certain criteria.
"""
input Inscripcion_ListFilter {
  """
  The desired number of objects that match the condition (defaults to at least one).
  """
  count: Int_Filter = {gt:0}
  """
  Condition of the related objects to filter for.
  """
  exist: Inscripcion_Filter
}
"""
✨ Generated order input type for table 'Inscripcion'. This input defines the sorting order of rows in query results based on one or more fields.
"""
input Inscripcion_Order {
  """
  ✨ Generated from Field `Inscripcion`.`id` of type `UUID!`
  """
  id: OrderDirection
  """
  ✨ Generated from Field `Inscripcion`.`estudianteId` of type `UUID!`
  """
  estudianteId: OrderDirection
  """
  ✨ Generated from Field `Inscripcion`.`horarioId` of type `UUID!`
  """
  horarioId: OrderDirection
  """
  ✨ Generated from Field `Inscripcion`.`estudiante` of type `Estudiante!`
  """
  estudiante: Estudiante_Order
  """
  ✨ Generated from Field `Inscripcion`.`horario` of type `Horario!`
  """
  horario: Horario_Order
  """
  ✨ Generated from Field `Inscripcion`.`estadoInscripcion` of type `String!`
  """
  estadoInscripcion: OrderDirection
  """
  ✨ Generated from Field `Inscripcion`.`fechaInscripcion` of type `Date!`
  """
  fechaInscripcion: OrderDirection
  """
  ✨ Generated from Field `Inscripcion`.`inscripcionId` of type `String!`
  """
  inscripcionId: OrderDirection
  """
  ✨ Generated from Field `Inscripcion`.`pagoEstado` of type `String`
  """
  pagoEstado: OrderDirection
  """
  ✨ Generated from Field `Inscripcion`.`_count` of type `Int!`
  """
  _count: OrderDirection
  """
  ✨ Generated from Field `Inscripcion`.`estadoInscripcion_count` of type `Int!`
  """
  estadoInscripcion_count: OrderDirection
  """
  ✨ Generated from Field `Inscripcion`.`estudianteId_count` of type `Int!`
  """
  estudianteId_count: OrderDirection
  """
  ✨ Generated from Field `Inscripcion`.`fechaInscripcion_count` of type `Int!`
  """
  fechaInscripcion_count: OrderDirection
  """
  ✨ Generated from Field `Inscripcion`.`horarioId_count` of type `Int!`
  """
  horarioId_count: OrderDirection
  """
  ✨ Generated from Field `Inscripcion`.`id_count` of type `Int!`
  """
  id_count: OrderDirection
  """
  ✨ Generated from Field `Inscripcion`.`inscripcionId_count` of type `Int!`
  """
  inscripcionId_count: OrderDirection
  """
  ✨ Generated from Field `Inscripcion`.`pagoEstado_count` of type `Int!`
  """
  pagoEstado_count: OrderDirection
  """
  ✨ Generated from Field `Inscripcion`.`fechaInscripcion_min` of type `Date`
  """
  fechaInscripcion_min: OrderDirection
  """
  ✨ Generated from Field `Inscripcion`.`fechaInscripcion_max` of type `Date`
  """
  fechaInscripcion_max: OrderDirection
}
"""
✨ Generated data input type for table 'Instructor'. It includes all necessary fields for creating or upserting rows into table.
"""
input Instructor_Data {
  """
  ✨ Generated from Field `Instructor`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `Instructor`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Instructor`.`activo` of type `Boolean!`
  """
  activo: Boolean
  """
  ✨ `_expr` server value variant of `activo` (✨ Generated from Field `Instructor`.`activo` of type `Boolean!`)
  """
  activo_expr: Boolean_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Instructor`.`correo` of type `String!`
  """
  correo: String
  """
  ✨ `_expr` server value variant of `correo` (✨ Generated from Field `Instructor`.`correo` of type `String!`)
  """
  correo_expr: String_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Instructor`.`especialidad` of type `String`
  """
  especialidad: String
  """
  ✨ `_expr` server value variant of `especialidad` (✨ Generated from Field `Instructor`.`especialidad` of type `String`)
  """
  especialidad_expr: String_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Instructor`.`instructorId` of type `Int!`
  """
  instructorId: Int
  """
  ✨ `_expr` server value variant of `instructorId` (✨ Generated from Field `Instructor`.`instructorId` of type `Int!`)
  """
  instructorId_expr: Int_Expr @fdc_forbiddenInVariables
  """
  ✨ `_update` server value variant of `instructorId` (✨ Generated from Field `Instructor`.`instructorId` of type `Int!`)
  """
  instructorId_update: [Int_Update!] @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Instructor`.`nombreCompleto` of type `String!`
  """
  nombreCompleto: String
  """
  ✨ `_expr` server value variant of `nombreCompleto` (✨ Generated from Field `Instructor`.`nombreCompleto` of type `String!`)
  """
  nombreCompleto_expr: String_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Instructor`.`telefono` of type `String`
  """
  telefono: String
  """
  ✨ `_expr` server value variant of `telefono` (✨ Generated from Field `Instructor`.`telefono` of type `String`)
  """
  telefono_expr: String_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Instructor`.`asistencias_on_instructor` of type `[Asistencia!]!`
  """
  asistencias_on_instructor: [Asistencia_Data!]
}
"""
✨ Generated filter input type for table 'Instructor'. This input allows filtering objects using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input Instructor_Filter {
  """
  Apply multiple filter conditions using `AND` logic.
  """
  _and: [Instructor_Filter!]
  """
  Negate the result of the provided filter condition.
  """
  _not: Instructor_Filter
  """
  Apply multiple filter conditions using `OR` logic.
  """
  _or: [Instructor_Filter!]
  """
  ✨ Generated from Field `Instructor`.`id` of type `UUID!`
  """
  id: UUID_Filter
  """
  ✨ Generated from Field `Instructor`.`activo` of type `Boolean!`
  """
  activo: Boolean_Filter
  """
  ✨ Generated from Field `Instructor`.`correo` of type `String!`
  """
  correo: String_Filter
  """
  ✨ Generated from Field `Instructor`.`especialidad` of type `String`
  """
  especialidad: String_Filter
  """
  ✨ Generated from Field `Instructor`.`instructorId` of type `Int!`
  """
  instructorId: Int_Filter
  """
  ✨ Generated from Field `Instructor`.`nombreCompleto` of type `String!`
  """
  nombreCompleto: String_Filter
  """
  ✨ Generated from Field `Instructor`.`telefono` of type `String`
  """
  telefono: String_Filter
  """
  ✨ Generated from Field `Instructor`.`asistencias_on_instructor` of type `[Asistencia!]!`
  """
  asistencias_on_instructor: Asistencia_ListFilter
}
"""
✨ Generated first-row input type for table 'Instructor'. This input selects the first row matching the filter criteria, ordered according to the specified conditions.
"""
input Instructor_FirstRow {
  """
  Order the result by the specified fields.
  """
  orderBy: [Instructor_Order!]
  """
  Filters rows based on the specified conditions.
  """
  where: Instructor_Filter
}
"""
✨ Generated having input type for table 'Instructor'. This input allows you to filter groups during aggregate queries using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input Instructor_Having {
  """
  Apply multiple Having conditions using `AND` logic.
  """
  _and: [Instructor_Having!]
  """
  Whether to apply DISTINCT to the aggregate function.
  """
  _distinct: Boolean
  """
  Negate the result of the provided Having condition.
  """
  _not: Instructor_Having
  """
  Apply multiple Having conditions using `OR` logic.
  """
  _or: [Instructor_Having!]
  """
  ✨ Generated from Field `Instructor`.`_count` of type `Int!`
  """
  _count: Int_Filter
  """
  ✨ Generated from Field `Instructor`.`activo_count` of type `Int!`
  """
  activo_count: Int_Filter
  """
  ✨ Generated from Field `Instructor`.`correo_count` of type `Int!`
  """
  correo_count: Int_Filter
  """
  ✨ Generated from Field `Instructor`.`especialidad_count` of type `Int!`
  """
  especialidad_count: Int_Filter
  """
  ✨ Generated from Field `Instructor`.`id_count` of type `Int!`
  """
  id_count: Int_Filter
  """
  ✨ Generated from Field `Instructor`.`instructorId_count` of type `Int!`
  """
  instructorId_count: Int_Filter
  """
  ✨ Generated from Field `Instructor`.`nombreCompleto_count` of type `Int!`
  """
  nombreCompleto_count: Int_Filter
  """
  ✨ Generated from Field `Instructor`.`telefono_count` of type `Int!`
  """
  telefono_count: Int_Filter
  """
  ✨ Generated from Field `Instructor`.`instructorId_sum` of type `Int`
  """
  instructorId_sum: Int_Filter
  """
  ✨ Generated from Field `Instructor`.`instructorId_avg` of type `Float`
  """
  instructorId_avg: Float_Filter
  """
  ✨ Generated from Field `Instructor`.`instructorId_min` of type `Int`
  """
  instructorId_min: Int_Filter
  """
  ✨ Generated from Field `Instructor`.`instructorId_max` of type `Int`
  """
  instructorId_max: Int_Filter
}
"""
✨ Generated key input type for table 'Instructor'. It represents the primary key fields used to uniquely identify a row in the table.
"""
input Instructor_Key {
  """
  ✨ Generated from Field `Instructor`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `Instructor`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr @fdc_forbiddenInVariables
}
"""
✨ Generated list filter input type for table 'Instructor'. This input applies filtering logic based on the count or existence of related objects that matches certain criteria.
"""
input Instructor_ListFilter {
  """
  The desired number of objects that match the condition (defaults to at least one).
  """
  count: Int_Filter = {gt:0}
  """
  Condition of the related objects to filter for.
  """
  exist: Instructor_Filter
}
"""
✨ Generated order input type for table 'Instructor'. This input defines the sorting order of rows in query results based on one or more fields.
"""
input Instructor_Order {
  """
  ✨ Generated from Field `Instructor`.`id` of type `UUID!`
  """
  id: OrderDirection
  """
  ✨ Generated from Field `Instructor`.`activo` of type `Boolean!`
  """
  activo: OrderDirection
  """
  ✨ Generated from Field `Instructor`.`correo` of type `String!`
  """
  correo: OrderDirection
  """
  ✨ Generated from Field `Instructor`.`especialidad` of type `String`
  """
  especialidad: OrderDirection
  """
  ✨ Generated from Field `Instructor`.`instructorId` of type `Int!`
  """
  instructorId: OrderDirection
  """
  ✨ Generated from Field `Instructor`.`nombreCompleto` of type `String!`
  """
  nombreCompleto: OrderDirection
  """
  ✨ Generated from Field `Instructor`.`telefono` of type `String`
  """
  telefono: OrderDirection
  """
  ✨ Generated from Field `Instructor`.`_count` of type `Int!`
  """
  _count: OrderDirection
  """
  ✨ Generated from Field `Instructor`.`activo_count` of type `Int!`
  """
  activo_count: OrderDirection
  """
  ✨ Generated from Field `Instructor`.`correo_count` of type `Int!`
  """
  correo_count: OrderDirection
  """
  ✨ Generated from Field `Instructor`.`especialidad_count` of type `Int!`
  """
  especialidad_count: OrderDirection
  """
  ✨ Generated from Field `Instructor`.`id_count` of type `Int!`
  """
  id_count: OrderDirection
  """
  ✨ Generated from Field `Instructor`.`instructorId_count` of type `Int!`
  """
  instructorId_count: OrderDirection
  """
  ✨ Generated from Field `Instructor`.`nombreCompleto_count` of type `Int!`
  """
  nombreCompleto_count: OrderDirection
  """
  ✨ Generated from Field `Instructor`.`telefono_count` of type `Int!`
  """
  telefono_count: OrderDirection
  """
  ✨ Generated from Field `Instructor`.`instructorId_sum` of type `Int`
  """
  instructorId_sum: OrderDirection
  """
  ✨ Generated from Field `Instructor`.`instructorId_avg` of type `Float`
  """
  instructorId_avg: OrderDirection
  """
  ✨ Generated from Field `Instructor`.`instructorId_min` of type `Int`
  """
  instructorId_min: OrderDirection
  """
  ✨ Generated from Field `Instructor`.`instructorId_max` of type `Int`
  """
  instructorId_max: OrderDirection
}
"""
✨ Generated data input type for table 'ReporteEstadistica'. It includes all necessary fields for creating or upserting rows into table.
"""
input ReporteEstadistica_Data {
  """
  ✨ Generated from Field `ReporteEstadistica`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `ReporteEstadistica`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `ReporteEstadistica`.`cursoId` of type `UUID!`
  """
  cursoId: UUID
  """
  ✨ `_expr` server value variant of `cursoId` (✨ Generated from Field `ReporteEstadistica`.`cursoId` of type `UUID!`)
  """
  cursoId_expr: UUID_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `ReporteEstadistica`.`curso` of type `Curso!`
  """
  curso: Curso_Key @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `ReporteEstadistica`.`calificacionPromedio` of type `Float`
  """
  calificacionPromedio: Float
  """
  ✨ `_expr` server value variant of `calificacionPromedio` (✨ Generated from Field `ReporteEstadistica`.`calificacionPromedio` of type `Float`)
  """
  calificacionPromedio_expr: Float_Expr @fdc_forbiddenInVariables
  """
  ✨ `_update` server value variant of `calificacionPromedio` (✨ Generated from Field `ReporteEstadistica`.`calificacionPromedio` of type `Float`)
  """
  calificacionPromedio_update: [Float_Update!] @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `ReporteEstadistica`.`fechaActualizacion` of type `Date!`
  """
  fechaActualizacion: Date
  """
  ✨ `_date` server value variant of `fechaActualizacion` (✨ Generated from Field `ReporteEstadistica`.`fechaActualizacion` of type `Date!`)
  """
  fechaActualizacion_date: Date_Relative @fdc_forbiddenInVariables
  """
  ✨ `_expr` server value variant of `fechaActualizacion` (✨ Generated from Field `ReporteEstadistica`.`fechaActualizacion` of type `Date!`)
  """
  fechaActualizacion_expr: Date_Expr @fdc_forbiddenInVariables
  """
  ✨ `_update` server value variant of `fechaActualizacion` (✨ Generated from Field `ReporteEstadistica`.`fechaActualizacion` of type `Date!`)
  """
  fechaActualizacion_update: [Date_Update!] @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `ReporteEstadistica`.`ingresosGenerados` of type `Float`
  """
  ingresosGenerados: Float
  """
  ✨ `_expr` server value variant of `ingresosGenerados` (✨ Generated from Field `ReporteEstadistica`.`ingresosGenerados` of type `Float`)
  """
  ingresosGenerados_expr: Float_Expr @fdc_forbiddenInVariables
  """
  ✨ `_update` server value variant of `ingresosGenerados` (✨ Generated from Field `ReporteEstadistica`.`ingresosGenerados` of type `Float`)
  """
  ingresosGenerados_update: [Float_Update!] @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `ReporteEstadistica`.`periodoAnio` of type `String!`
  """
  periodoAnio: String
  """
  ✨ `_expr` server value variant of `periodoAnio` (✨ Generated from Field `ReporteEstadistica`.`periodoAnio` of type `String!`)
  """
  periodoAnio_expr: String_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `ReporteEstadistica`.`porcentajeAsistencia` of type `Float!`
  """
  porcentajeAsistencia: Float
  """
  ✨ `_expr` server value variant of `porcentajeAsistencia` (✨ Generated from Field `ReporteEstadistica`.`porcentajeAsistencia` of type `Float!`)
  """
  porcentajeAsistencia_expr: Float_Expr @fdc_forbiddenInVariables
  """
  ✨ `_update` server value variant of `porcentajeAsistencia` (✨ Generated from Field `ReporteEstadistica`.`porcentajeAsistencia` of type `Float!`)
  """
  porcentajeAsistencia_update: [Float_Update!] @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `ReporteEstadistica`.`reporteId` of type `Int!`
  """
  reporteId: Int
  """
  ✨ `_expr` server value variant of `reporteId` (✨ Generated from Field `ReporteEstadistica`.`reporteId` of type `Int!`)
  """
  reporteId_expr: Int_Expr @fdc_forbiddenInVariables
  """
  ✨ `_update` server value variant of `reporteId` (✨ Generated from Field `ReporteEstadistica`.`reporteId` of type `Int!`)
  """
  reporteId_update: [Int_Update!] @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `ReporteEstadistica`.`totalBajas` of type `Int!`
  """
  totalBajas: Int
  """
  ✨ `_expr` server value variant of `totalBajas` (✨ Generated from Field `ReporteEstadistica`.`totalBajas` of type `Int!`)
  """
  totalBajas_expr: Int_Expr @fdc_forbiddenInVariables
  """
  ✨ `_update` server value variant of `totalBajas` (✨ Generated from Field `ReporteEstadistica`.`totalBajas` of type `Int!`)
  """
  totalBajas_update: [Int_Update!] @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `ReporteEstadistica`.`totalInscritos` of type `Int!`
  """
  totalInscritos: Int
  """
  ✨ `_expr` server value variant of `totalInscritos` (✨ Generated from Field `ReporteEstadistica`.`totalInscritos` of type `Int!`)
  """
  totalInscritos_expr: Int_Expr @fdc_forbiddenInVariables
  """
  ✨ `_update` server value variant of `totalInscritos` (✨ Generated from Field `ReporteEstadistica`.`totalInscritos` of type `Int!`)
  """
  totalInscritos_update: [Int_Update!] @fdc_forbiddenInVariables
}
"""
✨ Generated filter input type for table 'ReporteEstadistica'. This input allows filtering objects using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input ReporteEstadistica_Filter {
  """
  Apply multiple filter conditions using `AND` logic.
  """
  _and: [ReporteEstadistica_Filter!]
  """
  Negate the result of the provided filter condition.
  """
  _not: ReporteEstadistica_Filter
  """
  Apply multiple filter conditions using `OR` logic.
  """
  _or: [ReporteEstadistica_Filter!]
  """
  ✨ Generated from Field `ReporteEstadistica`.`id` of type `UUID!`
  """
  id: UUID_Filter
  """
  ✨ Generated from Field `ReporteEstadistica`.`cursoId` of type `UUID!`
  """
  cursoId: UUID_Filter
  """
  ✨ Generated from Field `ReporteEstadistica`.`curso` of type `Curso!`
  """
  curso: Curso_Filter
  """
  ✨ Generated from Field `ReporteEstadistica`.`calificacionPromedio` of type `Float`
  """
  calificacionPromedio: Float_Filter
  """
  ✨ Generated from Field `ReporteEstadistica`.`fechaActualizacion` of type `Date!`
  """
  fechaActualizacion: Date_Filter
  """
  ✨ Generated from Field `ReporteEstadistica`.`ingresosGenerados` of type `Float`
  """
  ingresosGenerados: Float_Filter
  """
  ✨ Generated from Field `ReporteEstadistica`.`periodoAnio` of type `String!`
  """
  periodoAnio: String_Filter
  """
  ✨ Generated from Field `ReporteEstadistica`.`porcentajeAsistencia` of type `Float!`
  """
  porcentajeAsistencia: Float_Filter
  """
  ✨ Generated from Field `ReporteEstadistica`.`reporteId` of type `Int!`
  """
  reporteId: Int_Filter
  """
  ✨ Generated from Field `ReporteEstadistica`.`totalBajas` of type `Int!`
  """
  totalBajas: Int_Filter
  """
  ✨ Generated from Field `ReporteEstadistica`.`totalInscritos` of type `Int!`
  """
  totalInscritos: Int_Filter
}
"""
✨ Generated first-row input type for table 'ReporteEstadistica'. This input selects the first row matching the filter criteria, ordered according to the specified conditions.
"""
input ReporteEstadistica_FirstRow {
  """
  Order the result by the specified fields.
  """
  orderBy: [ReporteEstadistica_Order!]
  """
  Filters rows based on the specified conditions.
  """
  where: ReporteEstadistica_Filter
}
"""
✨ Generated having input type for table 'ReporteEstadistica'. This input allows you to filter groups during aggregate queries using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input ReporteEstadistica_Having {
  """
  Apply multiple Having conditions using `AND` logic.
  """
  _and: [ReporteEstadistica_Having!]
  """
  Whether to apply DISTINCT to the aggregate function.
  """
  _distinct: Boolean
  """
  Negate the result of the provided Having condition.
  """
  _not: ReporteEstadistica_Having
  """
  Apply multiple Having conditions using `OR` logic.
  """
  _or: [ReporteEstadistica_Having!]
  """
  ✨ Generated from Field `ReporteEstadistica`.`_count` of type `Int!`
  """
  _count: Int_Filter
  """
  ✨ Generated from Field `ReporteEstadistica`.`calificacionPromedio_count` of type `Int!`
  """
  calificacionPromedio_count: Int_Filter
  """
  ✨ Generated from Field `ReporteEstadistica`.`cursoId_count` of type `Int!`
  """
  cursoId_count: Int_Filter
  """
  ✨ Generated from Field `ReporteEstadistica`.`fechaActualizacion_count` of type `Int!`
  """
  fechaActualizacion_count: Int_Filter
  """
  ✨ Generated from Field `ReporteEstadistica`.`id_count` of type `Int!`
  """
  id_count: Int_Filter
  """
  ✨ Generated from Field `ReporteEstadistica`.`ingresosGenerados_count` of type `Int!`
  """
  ingresosGenerados_count: Int_Filter
  """
  ✨ Generated from Field `ReporteEstadistica`.`periodoAnio_count` of type `Int!`
  """
  periodoAnio_count: Int_Filter
  """
  ✨ Generated from Field `ReporteEstadistica`.`porcentajeAsistencia_count` of type `Int!`
  """
  porcentajeAsistencia_count: Int_Filter
  """
  ✨ Generated from Field `ReporteEstadistica`.`reporteId_count` of type `Int!`
  """
  reporteId_count: Int_Filter
  """
  ✨ Generated from Field `ReporteEstadistica`.`totalBajas_count` of type `Int!`
  """
  totalBajas_count: Int_Filter
  """
  ✨ Generated from Field `ReporteEstadistica`.`totalInscritos_count` of type `Int!`
  """
  totalInscritos_count: Int_Filter
  """
  ✨ Generated from Field `ReporteEstadistica`.`calificacionPromedio_sum` of type `Float`
  """
  calificacionPromedio_sum: Float_Filter
  """
  ✨ Generated from Field `ReporteEstadistica`.`ingresosGenerados_sum` of type `Float`
  """
  ingresosGenerados_sum: Float_Filter
  """
  ✨ Generated from Field `ReporteEstadistica`.`porcentajeAsistencia_sum` of type `Float`
  """
  porcentajeAsistencia_sum: Float_Filter
  """
  ✨ Generated from Field `ReporteEstadistica`.`reporteId_sum` of type `Int`
  """
  reporteId_sum: Int_Filter
  """
  ✨ Generated from Field `ReporteEstadistica`.`totalBajas_sum` of type `Int`
  """
  totalBajas_sum: Int_Filter
  """
  ✨ Generated from Field `ReporteEstadistica`.`totalInscritos_sum` of type `Int`
  """
  totalInscritos_sum: Int_Filter
  """
  ✨ Generated from Field `ReporteEstadistica`.`calificacionPromedio_avg` of type `Float`
  """
  calificacionPromedio_avg: Float_Filter
  """
  ✨ Generated from Field `ReporteEstadistica`.`ingresosGenerados_avg` of type `Float`
  """
  ingresosGenerados_avg: Float_Filter
  """
  ✨ Generated from Field `ReporteEstadistica`.`porcentajeAsistencia_avg` of type `Float`
  """
  porcentajeAsistencia_avg: Float_Filter
  """
  ✨ Generated from Field `ReporteEstadistica`.`reporteId_avg` of type `Float`
  """
  reporteId_avg: Float_Filter
  """
  ✨ Generated from Field `ReporteEstadistica`.`totalBajas_avg` of type `Float`
  """
  totalBajas_avg: Float_Filter
  """
  ✨ Generated from Field `ReporteEstadistica`.`totalInscritos_avg` of type `Float`
  """
  totalInscritos_avg: Float_Filter
  """
  ✨ Generated from Field `ReporteEstadistica`.`calificacionPromedio_min` of type `Float`
  """
  calificacionPromedio_min: Float_Filter
  """
  ✨ Generated from Field `ReporteEstadistica`.`fechaActualizacion_min` of type `Date`
  """
  fechaActualizacion_min: Date_Filter
  """
  ✨ Generated from Field `ReporteEstadistica`.`ingresosGenerados_min` of type `Float`
  """
  ingresosGenerados_min: Float_Filter
  """
  ✨ Generated from Field `ReporteEstadistica`.`porcentajeAsistencia_min` of type `Float`
  """
  porcentajeAsistencia_min: Float_Filter
  """
  ✨ Generated from Field `ReporteEstadistica`.`reporteId_min` of type `Int`
  """
  reporteId_min: Int_Filter
  """
  ✨ Generated from Field `ReporteEstadistica`.`totalBajas_min` of type `Int`
  """
  totalBajas_min: Int_Filter
  """
  ✨ Generated from Field `ReporteEstadistica`.`totalInscritos_min` of type `Int`
  """
  totalInscritos_min: Int_Filter
  """
  ✨ Generated from Field `ReporteEstadistica`.`calificacionPromedio_max` of type `Float`
  """
  calificacionPromedio_max: Float_Filter
  """
  ✨ Generated from Field `ReporteEstadistica`.`fechaActualizacion_max` of type `Date`
  """
  fechaActualizacion_max: Date_Filter
  """
  ✨ Generated from Field `ReporteEstadistica`.`ingresosGenerados_max` of type `Float`
  """
  ingresosGenerados_max: Float_Filter
  """
  ✨ Generated from Field `ReporteEstadistica`.`porcentajeAsistencia_max` of type `Float`
  """
  porcentajeAsistencia_max: Float_Filter
  """
  ✨ Generated from Field `ReporteEstadistica`.`reporteId_max` of type `Int`
  """
  reporteId_max: Int_Filter
  """
  ✨ Generated from Field `ReporteEstadistica`.`totalBajas_max` of type `Int`
  """
  totalBajas_max: Int_Filter
  """
  ✨ Generated from Field `ReporteEstadistica`.`totalInscritos_max` of type `Int`
  """
  totalInscritos_max: Int_Filter
}
"""
✨ Generated key input type for table 'ReporteEstadistica'. It represents the primary key fields used to uniquely identify a row in the table.
"""
input ReporteEstadistica_Key {
  """
  ✨ Generated from Field `ReporteEstadistica`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `ReporteEstadistica`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr @fdc_forbiddenInVariables
}
"""
✨ Generated list filter input type for table 'ReporteEstadistica'. This input applies filtering logic based on the count or existence of related objects that matches certain criteria.
"""
input ReporteEstadistica_ListFilter {
  """
  The desired number of objects that match the condition (defaults to at least one).
  """
  count: Int_Filter = {gt:0}
  """
  Condition of the related objects to filter for.
  """
  exist: ReporteEstadistica_Filter
}
"""
✨ Generated order input type for table 'ReporteEstadistica'. This input defines the sorting order of rows in query results based on one or more fields.
"""
input ReporteEstadistica_Order {
  """
  ✨ Generated from Field `ReporteEstadistica`.`id` of type `UUID!`
  """
  id: OrderDirection
  """
  ✨ Generated from Field `ReporteEstadistica`.`cursoId` of type `UUID!`
  """
  cursoId: OrderDirection
  """
  ✨ Generated from Field `ReporteEstadistica`.`curso` of type `Curso!`
  """
  curso: Curso_Order
  """
  ✨ Generated from Field `ReporteEstadistica`.`calificacionPromedio` of type `Float`
  """
  calificacionPromedio: OrderDirection
  """
  ✨ Generated from Field `ReporteEstadistica`.`fechaActualizacion` of type `Date!`
  """
  fechaActualizacion: OrderDirection
  """
  ✨ Generated from Field `ReporteEstadistica`.`ingresosGenerados` of type `Float`
  """
  ingresosGenerados: OrderDirection
  """
  ✨ Generated from Field `ReporteEstadistica`.`periodoAnio` of type `String!`
  """
  periodoAnio: OrderDirection
  """
  ✨ Generated from Field `ReporteEstadistica`.`porcentajeAsistencia` of type `Float!`
  """
  porcentajeAsistencia: OrderDirection
  """
  ✨ Generated from Field `ReporteEstadistica`.`reporteId` of type `Int!`
  """
  reporteId: OrderDirection
  """
  ✨ Generated from Field `ReporteEstadistica`.`totalBajas` of type `Int!`
  """
  totalBajas: OrderDirection
  """
  ✨ Generated from Field `ReporteEstadistica`.`totalInscritos` of type `Int!`
  """
  totalInscritos: OrderDirection
  """
  ✨ Generated from Field `ReporteEstadistica`.`_count` of type `Int!`
  """
  _count: OrderDirection
  """
  ✨ Generated from Field `ReporteEstadistica`.`calificacionPromedio_count` of type `Int!`
  """
  calificacionPromedio_count: OrderDirection
  """
  ✨ Generated from Field `ReporteEstadistica`.`cursoId_count` of type `Int!`
  """
  cursoId_count: OrderDirection
  """
  ✨ Generated from Field `ReporteEstadistica`.`fechaActualizacion_count` of type `Int!`
  """
  fechaActualizacion_count: OrderDirection
  """
  ✨ Generated from Field `ReporteEstadistica`.`id_count` of type `Int!`
  """
  id_count: OrderDirection
  """
  ✨ Generated from Field `ReporteEstadistica`.`ingresosGenerados_count` of type `Int!`
  """
  ingresosGenerados_count: OrderDirection
  """
  ✨ Generated from Field `ReporteEstadistica`.`periodoAnio_count` of type `Int!`
  """
  periodoAnio_count: OrderDirection
  """
  ✨ Generated from Field `ReporteEstadistica`.`porcentajeAsistencia_count` of type `Int!`
  """
  porcentajeAsistencia_count: OrderDirection
  """
  ✨ Generated from Field `ReporteEstadistica`.`reporteId_count` of type `Int!`
  """
  reporteId_count: OrderDirection
  """
  ✨ Generated from Field `ReporteEstadistica`.`totalBajas_count` of type `Int!`
  """
  totalBajas_count: OrderDirection
  """
  ✨ Generated from Field `ReporteEstadistica`.`totalInscritos_count` of type `Int!`
  """
  totalInscritos_count: OrderDirection
  """
  ✨ Generated from Field `ReporteEstadistica`.`calificacionPromedio_sum` of type `Float`
  """
  calificacionPromedio_sum: OrderDirection
  """
  ✨ Generated from Field `ReporteEstadistica`.`ingresosGenerados_sum` of type `Float`
  """
  ingresosGenerados_sum: OrderDirection
  """
  ✨ Generated from Field `ReporteEstadistica`.`porcentajeAsistencia_sum` of type `Float`
  """
  porcentajeAsistencia_sum: OrderDirection
  """
  ✨ Generated from Field `ReporteEstadistica`.`reporteId_sum` of type `Int`
  """
  reporteId_sum: OrderDirection
  """
  ✨ Generated from Field `ReporteEstadistica`.`totalBajas_sum` of type `Int`
  """
  totalBajas_sum: OrderDirection
  """
  ✨ Generated from Field `ReporteEstadistica`.`totalInscritos_sum` of type `Int`
  """
  totalInscritos_sum: OrderDirection
  """
  ✨ Generated from Field `ReporteEstadistica`.`calificacionPromedio_avg` of type `Float`
  """
  calificacionPromedio_avg: OrderDirection
  """
  ✨ Generated from Field `ReporteEstadistica`.`ingresosGenerados_avg` of type `Float`
  """
  ingresosGenerados_avg: OrderDirection
  """
  ✨ Generated from Field `ReporteEstadistica`.`porcentajeAsistencia_avg` of type `Float`
  """
  porcentajeAsistencia_avg: OrderDirection
  """
  ✨ Generated from Field `ReporteEstadistica`.`reporteId_avg` of type `Float`
  """
  reporteId_avg: OrderDirection
  """
  ✨ Generated from Field `ReporteEstadistica`.`totalBajas_avg` of type `Float`
  """
  totalBajas_avg: OrderDirection
  """
  ✨ Generated from Field `ReporteEstadistica`.`totalInscritos_avg` of type `Float`
  """
  totalInscritos_avg: OrderDirection
  """
  ✨ Generated from Field `ReporteEstadistica`.`calificacionPromedio_min` of type `Float`
  """
  calificacionPromedio_min: OrderDirection
  """
  ✨ Generated from Field `ReporteEstadistica`.`fechaActualizacion_min` of type `Date`
  """
  fechaActualizacion_min: OrderDirection
  """
  ✨ Generated from Field `ReporteEstadistica`.`ingresosGenerados_min` of type `Float`
  """
  ingresosGenerados_min: OrderDirection
  """
  ✨ Generated from Field `ReporteEstadistica`.`porcentajeAsistencia_min` of type `Float`
  """
  porcentajeAsistencia_min: OrderDirection
  """
  ✨ Generated from Field `ReporteEstadistica`.`reporteId_min` of type `Int`
  """
  reporteId_min: OrderDirection
  """
  ✨ Generated from Field `ReporteEstadistica`.`totalBajas_min` of type `Int`
  """
  totalBajas_min: OrderDirection
  """
  ✨ Generated from Field `ReporteEstadistica`.`totalInscritos_min` of type `Int`
  """
  totalInscritos_min: OrderDirection
  """
  ✨ Generated from Field `ReporteEstadistica`.`calificacionPromedio_max` of type `Float`
  """
  calificacionPromedio_max: OrderDirection
  """
  ✨ Generated from Field `ReporteEstadistica`.`fechaActualizacion_max` of type `Date`
  """
  fechaActualizacion_max: OrderDirection
  """
  ✨ Generated from Field `ReporteEstadistica`.`ingresosGenerados_max` of type `Float`
  """
  ingresosGenerados_max: OrderDirection
  """
  ✨ Generated from Field `ReporteEstadistica`.`porcentajeAsistencia_max` of type `Float`
  """
  porcentajeAsistencia_max: OrderDirection
  """
  ✨ Generated from Field `ReporteEstadistica`.`reporteId_max` of type `Int`
  """
  reporteId_max: OrderDirection
  """
  ✨ Generated from Field `ReporteEstadistica`.`totalBajas_max` of type `Int`
  """
  totalBajas_max: OrderDirection
  """
  ✨ Generated from Field `ReporteEstadistica`.`totalInscritos_max` of type `Int`
  """
  totalInscritos_max: OrderDirection
}
