extend type Mutation {
  """
  ✨ Insert a single `Asistencia` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  asistencia_insert(
    """
    Data object to insert into the table.
    """
    data: Asistencia_Data!
  ): Asistencia_KeyOutput! @fdc_generated(from: "Asistencia", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `Curso` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  curso_insert(
    """
    Data object to insert into the table.
    """
    data: Curso_Data!
  ): Curso_KeyOutput! @fdc_generated(from: "Curso", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `Estudiante` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  estudiante_insert(
    """
    Data object to insert into the table.
    """
    data: Estudiante_Data!
  ): Estudiante_KeyOutput! @fdc_generated(from: "Estudiante", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `Horario` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  horario_insert(
    """
    Data object to insert into the table.
    """
    data: Horario_Data!
  ): Horario_KeyOutput! @fdc_generated(from: "Horario", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `Inscripcion` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  inscripcion_insert(
    """
    Data object to insert into the table.
    """
    data: Inscripcion_Data!
  ): Inscripcion_KeyOutput! @fdc_generated(from: "Inscripcion", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `Instructor` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  instructor_insert(
    """
    Data object to insert into the table.
    """
    data: Instructor_Data!
  ): Instructor_KeyOutput! @fdc_generated(from: "Instructor", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `ReporteEstadistica` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  reporteEstadistica_insert(
    """
    Data object to insert into the table.
    """
    data: ReporteEstadistica_Data!
  ): ReporteEstadistica_KeyOutput! @fdc_generated(from: "ReporteEstadistica", purpose: INSERT_SINGLE)
  """
  ✨ Insert `Asistencia` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  asistencia_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Asistencia_Data!]!
  ): [Asistencia_KeyOutput!]! @fdc_generated(from: "Asistencia", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `Curso` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  curso_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Curso_Data!]!
  ): [Curso_KeyOutput!]! @fdc_generated(from: "Curso", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `Estudiante` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  estudiante_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Estudiante_Data!]!
  ): [Estudiante_KeyOutput!]! @fdc_generated(from: "Estudiante", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `Horario` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  horario_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Horario_Data!]!
  ): [Horario_KeyOutput!]! @fdc_generated(from: "Horario", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `Inscripcion` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  inscripcion_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Inscripcion_Data!]!
  ): [Inscripcion_KeyOutput!]! @fdc_generated(from: "Inscripcion", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `Instructor` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  instructor_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Instructor_Data!]!
  ): [Instructor_KeyOutput!]! @fdc_generated(from: "Instructor", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `ReporteEstadistica` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  reporteEstadistica_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [ReporteEstadistica_Data!]!
  ): [ReporteEstadistica_KeyOutput!]! @fdc_generated(from: "ReporteEstadistica", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert or update a single `Asistencia` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Asistencia`.
  """
  asistencia_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Asistencia_Data!
  ): Asistencia_KeyOutput! @fdc_generated(from: "Asistencia", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `Curso` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Curso`.
  """
  curso_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Curso_Data!
  ): Curso_KeyOutput! @fdc_generated(from: "Curso", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `Estudiante` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Estudiante`.
  """
  estudiante_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Estudiante_Data!
  ): Estudiante_KeyOutput! @fdc_generated(from: "Estudiante", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `Horario` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Horario`.
  """
  horario_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Horario_Data!
  ): Horario_KeyOutput! @fdc_generated(from: "Horario", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `Inscripcion` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Inscripcion`.
  """
  inscripcion_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Inscripcion_Data!
  ): Inscripcion_KeyOutput! @fdc_generated(from: "Inscripcion", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `Instructor` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Instructor`.
  """
  instructor_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Instructor_Data!
  ): Instructor_KeyOutput! @fdc_generated(from: "Instructor", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `ReporteEstadistica` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `ReporteEstadistica`.
  """
  reporteEstadistica_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: ReporteEstadistica_Data!
  ): ReporteEstadistica_KeyOutput! @fdc_generated(from: "ReporteEstadistica", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update `Asistencia` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Asistencia`.
  """
  asistencia_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Asistencia_Data!]!
  ): [Asistencia_KeyOutput!]! @fdc_generated(from: "Asistencia", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `Curso` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Curso`.
  """
  curso_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Curso_Data!]!
  ): [Curso_KeyOutput!]! @fdc_generated(from: "Curso", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `Estudiante` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Estudiante`.
  """
  estudiante_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Estudiante_Data!]!
  ): [Estudiante_KeyOutput!]! @fdc_generated(from: "Estudiante", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `Horario` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Horario`.
  """
  horario_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Horario_Data!]!
  ): [Horario_KeyOutput!]! @fdc_generated(from: "Horario", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `Inscripcion` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Inscripcion`.
  """
  inscripcion_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Inscripcion_Data!]!
  ): [Inscripcion_KeyOutput!]! @fdc_generated(from: "Inscripcion", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `Instructor` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Instructor`.
  """
  instructor_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Instructor_Data!]!
  ): [Instructor_KeyOutput!]! @fdc_generated(from: "Instructor", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `ReporteEstadistica` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `ReporteEstadistica`.
  """
  reporteEstadistica_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [ReporteEstadistica_Data!]!
  ): [ReporteEstadistica_KeyOutput!]! @fdc_generated(from: "ReporteEstadistica", purpose: UPSERT_MULTIPLE)
  """
  ✨ Update a single `Asistencia` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Asistencia` or `null` if not found.
  """
  asistencia_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Asistencia_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Asistencia_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Asistencia_Data!
  ): Asistencia_KeyOutput @fdc_generated(from: "Asistencia", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `Curso` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Curso` or `null` if not found.
  """
  curso_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Curso_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Curso_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Curso_Data!
  ): Curso_KeyOutput @fdc_generated(from: "Curso", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `Estudiante` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Estudiante` or `null` if not found.
  """
  estudiante_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Estudiante_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Estudiante_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Estudiante_Data!
  ): Estudiante_KeyOutput @fdc_generated(from: "Estudiante", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `Horario` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Horario` or `null` if not found.
  """
  horario_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Horario_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Horario_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Horario_Data!
  ): Horario_KeyOutput @fdc_generated(from: "Horario", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `Inscripcion` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Inscripcion` or `null` if not found.
  """
  inscripcion_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Inscripcion_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Inscripcion_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Inscripcion_Data!
  ): Inscripcion_KeyOutput @fdc_generated(from: "Inscripcion", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `Instructor` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Instructor` or `null` if not found.
  """
  instructor_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Instructor_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Instructor_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Instructor_Data!
  ): Instructor_KeyOutput @fdc_generated(from: "Instructor", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `ReporteEstadistica` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `ReporteEstadistica` or `null` if not found.
  """
  reporteEstadistica_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: ReporteEstadistica_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: ReporteEstadistica_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: ReporteEstadistica_Data!
  ): ReporteEstadistica_KeyOutput @fdc_generated(from: "ReporteEstadistica", purpose: UPDATE_SINGLE)
  """
  ✨ Update `Asistencia` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  asistencia_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Asistencia_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Asistencia_Data!
  ): Int! @fdc_generated(from: "Asistencia", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `Curso` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  curso_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Curso_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Curso_Data!
  ): Int! @fdc_generated(from: "Curso", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `Estudiante` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  estudiante_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Estudiante_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Estudiante_Data!
  ): Int! @fdc_generated(from: "Estudiante", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `Horario` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  horario_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Horario_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Horario_Data!
  ): Int! @fdc_generated(from: "Horario", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `Inscripcion` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  inscripcion_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Inscripcion_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Inscripcion_Data!
  ): Int! @fdc_generated(from: "Inscripcion", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `Instructor` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  instructor_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Instructor_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Instructor_Data!
  ): Int! @fdc_generated(from: "Instructor", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `ReporteEstadistica` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  reporteEstadistica_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: ReporteEstadistica_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: ReporteEstadistica_Data!
  ): Int! @fdc_generated(from: "ReporteEstadistica", purpose: UPDATE_MULTIPLE)
  """
  ✨ Delete a single `Asistencia` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  asistencia_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Asistencia_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Asistencia_FirstRow
  ): Asistencia_KeyOutput @fdc_generated(from: "Asistencia", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `Curso` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  curso_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Curso_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Curso_FirstRow
  ): Curso_KeyOutput @fdc_generated(from: "Curso", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `Estudiante` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  estudiante_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Estudiante_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Estudiante_FirstRow
  ): Estudiante_KeyOutput @fdc_generated(from: "Estudiante", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `Horario` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  horario_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Horario_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Horario_FirstRow
  ): Horario_KeyOutput @fdc_generated(from: "Horario", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `Inscripcion` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  inscripcion_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Inscripcion_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Inscripcion_FirstRow
  ): Inscripcion_KeyOutput @fdc_generated(from: "Inscripcion", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `Instructor` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  instructor_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Instructor_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Instructor_FirstRow
  ): Instructor_KeyOutput @fdc_generated(from: "Instructor", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `ReporteEstadistica` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  reporteEstadistica_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: ReporteEstadistica_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: ReporteEstadistica_FirstRow
  ): ReporteEstadistica_KeyOutput @fdc_generated(from: "ReporteEstadistica", purpose: DELETE_SINGLE)
  """
  ✨ Delete `Asistencia` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  asistencia_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Asistencia_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Asistencia", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `Curso` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  curso_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Curso_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Curso", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `Estudiante` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  estudiante_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Estudiante_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Estudiante", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `Horario` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  horario_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Horario_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Horario", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `Inscripcion` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  inscripcion_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Inscripcion_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Inscripcion", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `Instructor` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  instructor_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Instructor_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Instructor", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `ReporteEstadistica` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  reporteEstadistica_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: ReporteEstadistica_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "ReporteEstadistica", purpose: DELETE_MULTIPLE)
}
