extend type Asistencia {
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "Asistencia", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `Asistencia` table.
  """
  _count: Int! @fdc_generated(from: "Asistencia.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Asistencia` table where the `asistenciaId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  asistenciaId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Asistencia.asistenciaId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Asistencia` table where the `estadoAsistencia` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  estadoAsistencia_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Asistencia.estadoAsistencia", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Asistencia` table where the `estudianteId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  estudianteId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Asistencia.estudianteId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Asistencia` table where the `fecha` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  fecha_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Asistencia.fecha", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Asistencia` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Asistencia.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Asistencia` table where the `instructorId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  instructorId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Asistencia.instructorId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Asistencia` table where the `materiaId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  materiaId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Asistencia.materiaId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Asistencia` table where the `observaciones` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  observaciones_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Asistencia.observaciones", purpose: QUERY_COUNT)
  """
  ✨ Sum the `asistenciaId` field in the `Asistencia` table.
  """
  asistenciaId_sum(
    """
    Set to true to sum the distinct values.
    """
    distinct: Boolean = false
  ): Int @fdc_generated(from: "Asistencia.asistenciaId", purpose: QUERY_SUM)
  """
  ✨ Sum the `materiaId` field in the `Asistencia` table.
  """
  materiaId_sum(
    """
    Set to true to sum the distinct values.
    """
    distinct: Boolean = false
  ): Int @fdc_generated(from: "Asistencia.materiaId", purpose: QUERY_SUM)
  """
  ✨ Average the `asistenciaId` field in the `Asistencia` table.
  """
  asistenciaId_avg(
    """
    Set to true to average the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "Asistencia.asistenciaId", purpose: QUERY_AVG)
  """
  ✨ Average the `materiaId` field in the `Asistencia` table.
  """
  materiaId_avg(
    """
    Set to true to average the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "Asistencia.materiaId", purpose: QUERY_AVG)
  """
  ✨ Minimum of the `asistenciaId` field in the `Asistencia` table.
  """
  asistenciaId_min: Int @fdc_generated(from: "Asistencia.asistenciaId", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `fecha` field in the `Asistencia` table.
  """
  fecha_min: Date @fdc_generated(from: "Asistencia.fecha", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `materiaId` field in the `Asistencia` table.
  """
  materiaId_min: Int @fdc_generated(from: "Asistencia.materiaId", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `asistenciaId` field in the `Asistencia` table.
  """
  asistenciaId_max: Int @fdc_generated(from: "Asistencia.asistenciaId", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `fecha` field in the `Asistencia` table.
  """
  fecha_max: Date @fdc_generated(from: "Asistencia.fecha", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `materiaId` field in the `Asistencia` table.
  """
  materiaId_max: Int @fdc_generated(from: "Asistencia.materiaId", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "Asistencia.id", purpose: ENTITY_ID)
}
extend type Curso {
  """
  ✨ List `Horario` objects in a one-to-many relationship (where `Horario`.`curso` is this object).
  """
  horarios_on_curso(
    """
    Filter condition to narrow down the query results.
    """
    where: Horario_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Horario_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Horario_Having
  ): [Horario!]! @fdc_generated(from: "Horario.curso", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "Curso", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `Curso` table.
  """
  _count: Int! @fdc_generated(from: "Curso.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Curso` table where the `categoria` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  categoria_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Curso.categoria", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Curso` table where the `cursoId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  cursoId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Curso.cursoId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Curso` table where the `descripcion` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  descripcion_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Curso.descripcion", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Curso` table where the `estado` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  estado_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Curso.estado", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Curso` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Curso.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Curso` table where the `instructor` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  instructor_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Curso.instructor", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Curso` table where the `nombre` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  nombre_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Curso.nombre", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Curso` table where the `urlImagen` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  urlImagen_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Curso.urlImagen", purpose: QUERY_COUNT)
  """
  ✨ Sum the `cursoId` field in the `Curso` table.
  """
  cursoId_sum(
    """
    Set to true to sum the distinct values.
    """
    distinct: Boolean = false
  ): Int @fdc_generated(from: "Curso.cursoId", purpose: QUERY_SUM)
  """
  ✨ Average the `cursoId` field in the `Curso` table.
  """
  cursoId_avg(
    """
    Set to true to average the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "Curso.cursoId", purpose: QUERY_AVG)
  """
  ✨ Minimum of the `cursoId` field in the `Curso` table.
  """
  cursoId_min: Int @fdc_generated(from: "Curso.cursoId", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `cursoId` field in the `Curso` table.
  """
  cursoId_max: Int @fdc_generated(from: "Curso.cursoId", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "Curso.id", purpose: ENTITY_ID)
}
extend type Estudiante {
  """
  ✨ List `Asistencia` objects in a one-to-many relationship (where `Asistencia`.`estudiante` is this object).
  """
  asistencias_on_estudiante(
    """
    Filter condition to narrow down the query results.
    """
    where: Asistencia_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Asistencia_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Asistencia_Having
  ): [Asistencia!]! @fdc_generated(from: "Asistencia.estudiante", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "Estudiante", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `Estudiante` table.
  """
  _count: Int! @fdc_generated(from: "Estudiante.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Estudiante` table where the `activo` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  activo_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Estudiante.activo", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Estudiante` table where the `correo` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  correo_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Estudiante.correo", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Estudiante` table where the `direccion` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  direccion_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Estudiante.direccion", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Estudiante` table where the `fechaNacimiento` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  fechaNacimiento_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Estudiante.fechaNacimiento", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Estudiante` table where the `fechaRegistro` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  fechaRegistro_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Estudiante.fechaRegistro", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Estudiante` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Estudiante.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Estudiante` table where the `matricula` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  matricula_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Estudiante.matricula", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Estudiante` table where the `nombreCompleto` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  nombreCompleto_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Estudiante.nombreCompleto", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Estudiante` table where the `telefono` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  telefono_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Estudiante.telefono", purpose: QUERY_COUNT)
  """
  ✨ Minimum of the `fechaNacimiento` field in the `Estudiante` table.
  """
  fechaNacimiento_min: Date @fdc_generated(from: "Estudiante.fechaNacimiento", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `fechaRegistro` field in the `Estudiante` table.
  """
  fechaRegistro_min: Date @fdc_generated(from: "Estudiante.fechaRegistro", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `fechaNacimiento` field in the `Estudiante` table.
  """
  fechaNacimiento_max: Date @fdc_generated(from: "Estudiante.fechaNacimiento", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `fechaRegistro` field in the `Estudiante` table.
  """
  fechaRegistro_max: Date @fdc_generated(from: "Estudiante.fechaRegistro", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "Estudiante.id", purpose: ENTITY_ID)
}
extend type Horario {
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "Horario", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `Horario` table.
  """
  _count: Int! @fdc_generated(from: "Horario.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Horario` table where the `cupoActual` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  cupoActual_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Horario.cupoActual", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Horario` table where the `cupoMaximo` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  cupoMaximo_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Horario.cupoMaximo", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Horario` table where the `cursoId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  cursoId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Horario.cursoId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Horario` table where the `estado` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  estado_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Horario.estado", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Horario` table where the `fechaFin` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  fechaFin_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Horario.fechaFin", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Horario` table where the `fechaInicio` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  fechaInicio_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Horario.fechaInicio", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Horario` table where the `horaFin` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  horaFin_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Horario.horaFin", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Horario` table where the `horaInicio` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  horaInicio_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Horario.horaInicio", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Horario` table where the `horarioId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  horarioId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Horario.horarioId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Horario` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Horario.id", purpose: QUERY_COUNT)
  """
  ✨ Sum the `cupoActual` field in the `Horario` table.
  """
  cupoActual_sum(
    """
    Set to true to sum the distinct values.
    """
    distinct: Boolean = false
  ): Int @fdc_generated(from: "Horario.cupoActual", purpose: QUERY_SUM)
  """
  ✨ Sum the `cupoMaximo` field in the `Horario` table.
  """
  cupoMaximo_sum(
    """
    Set to true to sum the distinct values.
    """
    distinct: Boolean = false
  ): Int @fdc_generated(from: "Horario.cupoMaximo", purpose: QUERY_SUM)
  """
  ✨ Sum the `horarioId` field in the `Horario` table.
  """
  horarioId_sum(
    """
    Set to true to sum the distinct values.
    """
    distinct: Boolean = false
  ): Int @fdc_generated(from: "Horario.horarioId", purpose: QUERY_SUM)
  """
  ✨ Average the `cupoActual` field in the `Horario` table.
  """
  cupoActual_avg(
    """
    Set to true to average the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "Horario.cupoActual", purpose: QUERY_AVG)
  """
  ✨ Average the `cupoMaximo` field in the `Horario` table.
  """
  cupoMaximo_avg(
    """
    Set to true to average the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "Horario.cupoMaximo", purpose: QUERY_AVG)
  """
  ✨ Average the `horarioId` field in the `Horario` table.
  """
  horarioId_avg(
    """
    Set to true to average the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "Horario.horarioId", purpose: QUERY_AVG)
  """
  ✨ Minimum of the `cupoActual` field in the `Horario` table.
  """
  cupoActual_min: Int @fdc_generated(from: "Horario.cupoActual", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `cupoMaximo` field in the `Horario` table.
  """
  cupoMaximo_min: Int @fdc_generated(from: "Horario.cupoMaximo", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `fechaFin` field in the `Horario` table.
  """
  fechaFin_min: Date @fdc_generated(from: "Horario.fechaFin", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `fechaInicio` field in the `Horario` table.
  """
  fechaInicio_min: Date @fdc_generated(from: "Horario.fechaInicio", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `horarioId` field in the `Horario` table.
  """
  horarioId_min: Int @fdc_generated(from: "Horario.horarioId", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `cupoActual` field in the `Horario` table.
  """
  cupoActual_max: Int @fdc_generated(from: "Horario.cupoActual", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `cupoMaximo` field in the `Horario` table.
  """
  cupoMaximo_max: Int @fdc_generated(from: "Horario.cupoMaximo", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `fechaFin` field in the `Horario` table.
  """
  fechaFin_max: Date @fdc_generated(from: "Horario.fechaFin", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `fechaInicio` field in the `Horario` table.
  """
  fechaInicio_max: Date @fdc_generated(from: "Horario.fechaInicio", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `horarioId` field in the `Horario` table.
  """
  horarioId_max: Int @fdc_generated(from: "Horario.horarioId", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "Horario.id", purpose: ENTITY_ID)
}
extend type Instructor {
  """
  ✨ List `Asistencia` objects in a one-to-many relationship (where `Asistencia`.`instructor` is this object).
  """
  asistencias_on_instructor(
    """
    Filter condition to narrow down the query results.
    """
    where: Asistencia_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Asistencia_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Asistencia_Having
  ): [Asistencia!]! @fdc_generated(from: "Asistencia.instructor", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "Instructor", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `Instructor` table.
  """
  _count: Int! @fdc_generated(from: "Instructor.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Instructor` table where the `activo` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  activo_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Instructor.activo", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Instructor` table where the `correo` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  correo_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Instructor.correo", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Instructor` table where the `especialidad` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  especialidad_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Instructor.especialidad", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Instructor` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Instructor.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Instructor` table where the `instructorId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  instructorId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Instructor.instructorId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Instructor` table where the `nombreCompleto` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  nombreCompleto_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Instructor.nombreCompleto", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Instructor` table where the `telefono` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  telefono_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Instructor.telefono", purpose: QUERY_COUNT)
  """
  ✨ Sum the `instructorId` field in the `Instructor` table.
  """
  instructorId_sum(
    """
    Set to true to sum the distinct values.
    """
    distinct: Boolean = false
  ): Int @fdc_generated(from: "Instructor.instructorId", purpose: QUERY_SUM)
  """
  ✨ Average the `instructorId` field in the `Instructor` table.
  """
  instructorId_avg(
    """
    Set to true to average the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "Instructor.instructorId", purpose: QUERY_AVG)
  """
  ✨ Minimum of the `instructorId` field in the `Instructor` table.
  """
  instructorId_min: Int @fdc_generated(from: "Instructor.instructorId", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `instructorId` field in the `Instructor` table.
  """
  instructorId_max: Int @fdc_generated(from: "Instructor.instructorId", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "Instructor.id", purpose: ENTITY_ID)
}
