type Estudiante @table {
  matricula: String! @unique
  nombreCompleto: String!
  correo: String! @unique
  telefono: String
  direccion: String
  fechaNacimiento: Date
  activo: Boolean! @default(value: true)
  fechaRegistro: Date! @default(expr: "request.time")
}

type Curso @table {
  cursoId: Int! @unique
  nombre: String!
  descripcion: String
  categoria: String
  urlImagen: String
  instructor: String
  estado: String

}

type Horario @table {
  horarioId: Int! @unique
  curso: Curso!
  fechaInicio: Date!
  fechaFin: Date!
  horaInicio: String!
  horaFin: String!
  cupoMaximo: Int!
  cupoActual: Int! @default(value: 0)
  estado: String
}

type Instructor @table {
  instructorId: Int! @unique
  nombreCompleto: String!
  correo: String! @unique
  telefono: String
  especialidad: String
  activo: Boolean! @default(value: true)
}

type Asistencia @table {
  asistenciaId: Int! @unique
  instructor: Instructor!
  estudiante: Estudiante!
  materiaId: Int! # El identificador numérico de la materia
  fecha: Date! @default(expr: "request.time")
  estadoAsistencia: String! # Aquí se guarda: "Presente", "Falta" o "Retardo"
  observaciones: String
}