type Estudiante @table {
  matricula: String! @unique
  nombreCompleto: String!
  correo: String! @unique
  telefono: String
  direccion: String
  fechaNacimiento: Date
  activo: Boolean! @default(value: true)
  fechaRegistro: Date! @default(expr: "request.time")
}

type Curso @table {
  cursoId: Int! @unique
  nombre: String!
  descripcion: String
  categoria: String
  urlImagen: String
  instructor: String
  estado: String

}

type Horario @table {
  horarioId: Int! @unique

  curso: Curso!

  fechaInicio: Date!
  fechaFin: Date!

  horaInicio: String!
  horaFin: String!

  cupoMaximo: Int!
  cupoActual: Int! @default(value: 0)

  estado: String
}